<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

class CreateProductIssuesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('product_issues', function (Blueprint $table) {
            $table->id();
            $table->string('category');
            $table->string('function');
            $table->text('issue');
            $table->timestamp('created_at')->default(DB::raw('CURRENT_TIMESTAMP'));
            $table->timestamp('updated_at')->default(DB::raw('CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP'));
        });

        DB::statement("INSERT INTO `product_issues` (`id`, `category`, `function`, `issue`) VALUES
        (1, 'Television', 'Audio', 'Audio out of sync'),
        (2, 'Television', 'Audio', 'Distorted Audio'),
        (3, 'Television', 'Audio', 'Low Audio'),
        (4, 'Television', 'Audio', 'No Audio'),
        (5, 'Television', 'Noise', 'Clicking / Knocking / Popping / Buzzing'),
        (6, 'Television', 'Noise', 'Hearing an echo'),
        (7, 'Television', 'Power', 'No Power'),
        (8, 'Television', 'Power', 'Intermittent Power or Power On / Offs'),
        (9, 'Television', 'Video Issue', 'Black & White Picture'),
        (10, 'Television', 'Video Issue', 'Dark or Dim Picture'),
        (11, 'Television', 'Video Issue', 'Image Ghosting'),
        (12, 'Television', 'Video Issue', 'No Video'),
        (13, 'Television', 'Video Issue', 'Picture Size or Aspect Ratio'),
        (14, 'Television', 'Video Issue', 'Poor Picture Quality'),
        (15, 'Television', 'Video Issue', 'Video Lag'),
        (16, 'Television', 'Video Issue', 'Power only Display'),
        (17, 'Television', 'Display', 'Lines in display'),
        (18, 'Television', 'Display', 'TV Screen Goes blank'),
        (19, 'Television', 'Display', 'Picture is pixelating or breaking up'),
        (20, 'Television', 'Display', 'TV Turns on But No Picture'),
        (21, 'Television', 'Display', 'Horizontal lines on start-up'),
        (22, 'Television', 'Connectivity', 'USB Issue'),
        (23, 'Television', 'Connectivity', 'Wifi connection not working'),
        (24, 'Television', 'Connectivity', 'HDMI 2.1 Ports Not Displaying Properly'),
        (25, 'Television', 'Apps / Playstore', 'Google Play Store Crashes During App Installation'),
        (26, 'Television', 'Apps / Playstore', 'Streaming Apps not Working'),
        (27, 'Television', 'Special Feature', '3D Glass Issue'),
        (28, 'Television', 'Special Feature', 'Web Browser Issue'),
        (29, 'Television', 'Special Feature', '3D Video Quality Issue'),
        (30, 'Air Conditioner', 'Power', 'Power supply trip'),
        (31, 'Air Conditioner', 'Power', 'Electric Shock'),
        (32, 'Air Conditioner', 'Power', 'Wire problem'),
        (33, 'Air Conditioner', 'Power', 'Won\'t power on'),
        (34, 'Air Conditioner', 'Power', 'Powers on, won\'t run'),
        (35, 'Air Conditioner', 'Power', 'Turns off abnormally'),
        (36, 'Air Conditioner', 'Power', 'Power Card reset switch (AFCI)'),
        (37, 'Air Conditioner', 'Power', 'Trips circuit breaker'),
        (38, 'Air Conditioner', 'Power', 'Turns off and on every couple of minutes'),
        (39, 'Air Conditioner', 'Power', 'Power cord reset switch (AFCI)'),
        (40, 'Air Conditioner', 'Power', 'Powers on and off abnormally'),
        (41, 'Air Conditioner', 'Power', 'Won\'t power off'),
        (42, 'Air Conditioner', 'Power', 'Intermittent power on/off'),
        (43, 'Air Conditioner', 'Power', 'Intermittent power'),
        (44, 'Air Conditioner', 'Power', 'Power supply volts too high'),
        (45, 'Air Conditioner', 'Power', 'Power supply volts too low'),
        (46, 'Air Conditioner', 'Temperature Issues', 'Condensation in Aircon Trunk'),
        (47, 'Air Conditioner', 'Temperature Issues', 'Air Conditioner Not Blowing Cold Air'),
        (48, 'Air Conditioner', 'Temperature Issues', 'Air Conditioner Freezing up Outside Unit'),
        (49, 'Air Conditioner', 'Temperature Issues', 'Not Cooling'),
        (50, 'Air Conditioner', 'Temperature Issues', 'Not Heating'),
        (51, 'Air Conditioner', 'Temperature Issues', 'Temperature Adjusts on its own'),
        (52, 'Air Conditioner', 'Temperature Issues', 'AI mode'),
        (53, 'Air Conditioner', 'Temperature Issues', 'Insufficient cooling'),
        (54, 'Air Conditioner', 'Temperature Issues', 'Insufficient heating'),
        (55, 'Air Conditioner', 'Temperature Issues', 'Set point error'),
        (56, 'Air Conditioner', 'Leaking', 'Misting (Smoking) from air vents'),
        (57, 'Air Conditioner', 'Leaking', 'Does not shut off when drain pan is full'),
        (58, 'Air Conditioner', 'Leaking', 'Spitting water out of front'),
        (59, 'Air Conditioner', 'Leaking', 'Indoor unit - water leakage'),
        (60, 'Air Conditioner', 'Leaking', 'Outdoor - water leakage'),
        (61, 'Air Conditioner', 'Leaking', 'Gas leak'),
        (62, 'Air Conditioner', 'Leaking', 'Water leaks from unit'),
        (63, 'Air Conditioner', 'Leaking', 'Leaks from Bucket'),
        (64, 'Air Conditioner', 'Leaking', 'Leaks from drain house connection'),
        (65, 'Air Conditioner', 'Leaking', 'Condensation from IDU'),
        (66, 'Air Conditioner', 'Leaking', 'Refrigerant - IDU coil'),
        (67, 'Air Conditioner', 'Leaking', 'Refrigerant - Line set'),
        (68, 'Air Conditioner', 'Leaking', 'Refrigerant - ODU coil'),
        (69, 'Air Conditioner', 'Leaking', 'Refrigerant - Service Valves'),
        (70, 'Air Conditioner', 'Leaking', 'Smoking'),
        (71, 'Air Conditioner', 'Leaking', 'Leaks from drain hose connection'),
        (72, 'Air Conditioner', 'Control Panel Issues', 'Blinking indicators or LEDs / Display do not light'),
        (73, 'Air Conditioner', 'Control Panel Issues', 'Buttons do not respond'),
        (74, 'Air Conditioner', 'Control Panel Issues', 'Error code - specific code in notes'),
        (75, 'Air Conditioner', 'Control Panel Issues', 'P2 or FL'),
        (76, 'Air Conditioner', 'Control Panel Issues', 'Controls do not respond'),
        (77, 'Air Conditioner', 'Control Panel Issues', 'Adjust settings'),
        (78, 'Air Conditioner', 'Odour', 'Bad Smell'),
        (79, 'Air Conditioner', 'Odour', 'Indoor unit - Foul smell'),
        (80, 'Air Conditioner', 'Remote Control', 'Remote control not working'),
        (81, 'Air Conditioner', 'Remote Control', 'Remote control - No Display'),
        (82, 'Air Conditioner', 'Breakage / Damage', 'Horizontal vane broken'),
        (83, 'Air Conditioner', 'Breakage / Damage', 'Body broken'),
        (84, 'Air Conditioner', 'Breakage / Damage', 'Body melted'),
        (85, 'Air Conditioner', 'Breakage / Damage', 'Color peel off'),
        (86, 'Air Conditioner', 'Breakage / Damage', 'Dented'),
        (87, 'Air Conditioner', 'Breakage / Damage', 'Disbalance'),
        (88, 'Air Conditioner', 'Breakage / Damage', 'Glass broken'),
        (89, 'Air Conditioner', 'Breakage / Damage', 'Jammed'),
        (90, 'Air Conditioner', 'Breakage / Damage', 'Horizontal vane not working'),
        (91, 'Air Conditioner', 'Breakage / Damage', 'Frozen Evaporator Coil'),
        (92, 'Air Conditioner', 'Sound / Noise', 'Humming'),
        (93, 'Air Conditioner', 'Sound / Noise', 'Knocking'),
        (94, 'Air Conditioner', 'Sound / Noise', 'Clicking'),
        (95, 'Air Conditioner', 'Sound / Noise', 'Buzzing'),
        (96, 'Air Conditioner', 'Sound / Noise', 'Compressor too loud'),
        (97, 'Air Conditioner', 'Sound / Noise', 'Squealing/High pitched sound'),
        (98, 'Air Conditioner', 'Sound / Noise', 'Line set'),
        (99, 'Air Conditioner', 'Sound / Noise', 'Unlisted (Specify in notes)'),
        (100, 'Air Conditioner', 'Sound / Noise', 'Rattling'),
        (101, 'Air Conditioner', 'Sound / Noise', 'Squealing'),
        (102, 'Air Conditioner', 'Sound / Noise', 'Indoor unit - Abnormal noise'),
        (103, 'Air Conditioner', 'Sound / Noise', 'Outdoor unit - Abnormal Noise'),
        (104, 'Air Conditioner', 'Operation', 'Adjusting temperature setting'),
        (105, 'Air Conditioner', 'Operation', 'Auto Mode'),
        (106, 'Air Conditioner', 'Operation', 'Cool Mode'),
        (107, 'Air Conditioner', 'Operation', 'Dehumidification Mode'),
        (108, 'Air Conditioner', 'Operation', 'Energy saver Mode'),
        (109, 'Air Conditioner', 'Operation', 'Fan Mode'),
        (110, 'Air Conditioner', 'Operation', 'Heat Mode'),
        (111, 'Air Conditioner', 'Operation', 'Remote Control'),
        (112, 'Air Conditioner', 'Operation', 'Sleep Mode'),
        (113, 'Air Conditioner', 'Operation', 'Timer'),
        (114, 'Air Conditioner', 'Operation', 'Fan runs all the time'),
        (115, 'Air Conditioner', 'Operation', 'Auto Restart'),
        (116, 'Air Conditioner', 'Operation', 'Outdoor fan cracked'),
        (117, 'Air Conditioner', 'Operation', 'Outdoor fan not moving'),
        (118, 'Air Conditioner', 'Operation', 'Does not Dehumidify'),
        (119, 'Air Conditioner', 'Operation', 'Heat from cabinet or Exhaust'),
        (120, 'Air Conditioner', 'Operation', 'Runs contantly or too much'),
        (121, 'Air Conditioner', 'Operation', 'Fan doesn\'t run'),
        (122, 'Air Conditioner', 'Operation', 'Mode'),
        (123, 'Air Conditioner', 'Settings', 'Fan speed'),
        (124, 'Air Conditioner', 'Settings', '2-4 way air deflection'),
        (125, 'Air Conditioner', 'Settings', 'Air purifier (PTAC)'),
        (126, 'Air Conditioner', 'Settings', 'Variable fan speeds'),
        (127, 'Air Conditioner', 'Settings', 'Heat pump doesn\'t engage'),
        (128, 'Air Conditioner', 'Settings', 'Indoor fan motor'),
        (129, 'Air Conditioner', 'CAC Leaking', 'Insufficient dehumidification'),
        (130, 'Air Conditioner', 'CAC Leaking', 'Outdoor coil leak'),
        (131, 'Air Conditioner', 'CAC Leaking', 'Refrigerant charge requirements'),
        (132, 'Air Conditioner', 'CAC Leaking', 'Pinging (water splashing)'),
        (133, 'Air Conditioner', 'CAC Leaking', 'Refrigerant - line set'),
        (134, 'Air Conditioner', 'CAC Leaking', 'Refrigerant - Service Valves'),
        (135, 'Air Conditioner', 'CAC Operation', 'Heat pump doesn\'t engage'),
        (136, 'Air Conditioner', 'CAC Operation', 'Indoor fan motor'),
        (137, 'Air Conditioner', 'CAC Operation', 'Ionizing Filter (PTAC)'),
        (138, 'Air Conditioner', 'Cooling', 'Air flow problem'),
        (139, 'Air Conditioner', 'Icing/Frost', 'Iced / Frosted behind front grille (Freezing up)'),
        (140, 'Air Conditioner', 'Icing/Frost', 'Iced / Frosted piping'),
        (141, 'Air Conditioner', 'Icing/Frost', 'Service valves/Line set'),
        (142, 'Commercial Air Conditioner', 'Power', 'Power supply trip'),
        (143, 'Commercial Air Conditioner', 'Power', 'Electric Shock'),
        (144, 'Commercial Air Conditioner', 'Power', 'Wire problem'),
        (145, 'Commercial Air Conditioner', 'Power', 'Won\'t power on'),
        (146, 'Commercial Air Conditioner', 'Power', 'Powers on, won\'t run'),
        (147, 'Commercial Air Conditioner', 'Power', 'Turns off abnormally'),
        (148, 'Commercial Air Conditioner', 'Power', 'Power Card reset switch (AFCI)'),
        (149, 'Commercial Air Conditioner', 'Power', 'Trips circuit breaker'),
        (150, 'Commercial Air Conditioner', 'Power', 'Turns off and on every couple of minutes'),
        (151, 'Commercial Air Conditioner', 'Power', 'Power cord reset switch (AFCI)'),
        (152, 'Commercial Air Conditioner', 'Power', 'Powers on and off abnormally'),
        (153, 'Commercial Air Conditioner', 'Power', 'Won\'t power off'),
        (154, 'Commercial Air Conditioner', 'Power', 'Intermittent power on/off'),
        (155, 'Commercial Air Conditioner', 'Power', 'Intermittent power'),
        (156, 'Commercial Air Conditioner', 'Power', 'Power supply volts too high'),
        (157, 'Commercial Air Conditioner', 'Power', 'Power supply volts too low'),
        (158, 'Commercial Air Conditioner', 'Temperature Issues', 'Condensation in Aircon Trunk'),
        (159, 'Commercial Air Conditioner', 'Temperature Issues', 'Air Conditioner Not Blowing Cold Air'),
        (160, 'Commercial Air Conditioner', 'Temperature Issues', 'Air Conditioner Freezing up Outside Unit'),
        (161, 'Commercial Air Conditioner', 'Temperature Issues', 'Not Cooling'),
        (162, 'Commercial Air Conditioner', 'Temperature Issues', 'Not Heating'),
        (163, 'Commercial Air Conditioner', 'Temperature Issues', 'Temperature Adjusts on its own'),
        (164, 'Commercial Air Conditioner', 'Temperature Issues', 'AI mode'),
        (165, 'Commercial Air Conditioner', 'Temperature Issues', 'Insufficient cooling'),
        (166, 'Commercial Air Conditioner', 'Temperature Issues', 'Insufficient heating'),
        (167, 'Commercial Air Conditioner', 'Temperature Issues', 'Set point error'),
        (168, 'Commercial Air Conditioner', 'Leaking', 'Misting (Smoking) from air vents'),
        (169, 'Commercial Air Conditioner', 'Leaking', 'Does not shut off when drain pan is full'),
        (170, 'Commercial Air Conditioner', 'Leaking', 'Spitting water out of front'),
        (171, 'Commercial Air Conditioner', 'Leaking', 'Indoor unit - water leakage'),
        (172, 'Commercial Air Conditioner', 'Leaking', 'Outdoor - water leakage'),
        (173, 'Commercial Air Conditioner', 'Leaking', 'Gas leak'),
        (174, 'Commercial Air Conditioner', 'Leaking', 'Water leaks from unit'),
        (175, 'Commercial Air Conditioner', 'Leaking', 'Leaks from Bucket'),
        (176, 'Commercial Air Conditioner', 'Leaking', 'Leaks from drain house connection'),
        (177, 'Commercial Air Conditioner', 'Leaking', 'Condensation from IDU'),
        (178, 'Commercial Air Conditioner', 'Leaking', 'Refrigerant - IDU coil'),
        (179, 'Commercial Air Conditioner', 'Leaking', 'Refrigerant - Line set'),
        (180, 'Commercial Air Conditioner', 'Leaking', 'Refrigerant - ODU coil'),
        (181, 'Commercial Air Conditioner', 'Leaking', 'Refrigerant - Service Valves'),
        (182, 'Commercial Air Conditioner', 'Leaking', 'Smoking'),
        (183, 'Commercial Air Conditioner', 'Leaking', 'Leaks from drain hose connection'),
        (184, 'Commercial Air Conditioner', 'Control Panel Issues', 'Blinking indicators or LEDs / Display do not light'),
        (185, 'Commercial Air Conditioner', 'Control Panel Issues', 'Buttons do not respond'),
        (186, 'Commercial Air Conditioner', 'Control Panel Issues', 'Error code - specific code in notes'),
        (187, 'Commercial Air Conditioner', 'Control Panel Issues', 'P2 or FL'),
        (188, 'Commercial Air Conditioner', 'Control Panel Issues', 'Controls do not respond'),
        (189, 'Commercial Air Conditioner', 'Control Panel Issues', 'Adjust settings'),
        (190, 'Commercial Air Conditioner', 'Odour', 'Bad Smell'),
        (191, 'Commercial Air Conditioner', 'Odour', 'Indoor unit - Foul smell'),
        (192, 'Commercial Air Conditioner', 'Remote Control', 'Remote control not working'),
        (193, 'Commercial Air Conditioner', 'Remote Control', 'Remote control - No Display'),
        (194, 'Commercial Air Conditioner', 'Breakage / Damage', 'Horizontal vane broken'),
        (195, 'Commercial Air Conditioner', 'Breakage / Damage', 'Body broken'),
        (196, 'Commercial Air Conditioner', 'Breakage / Damage', 'Body melted'),
        (197, 'Commercial Air Conditioner', 'Breakage / Damage', 'Color peel off'),
        (198, 'Commercial Air Conditioner', 'Breakage / Damage', 'Dented'),
        (199, 'Commercial Air Conditioner', 'Breakage / Damage', 'Disbalance'),
        (200, 'Commercial Air Conditioner', 'Breakage / Damage', 'Glass broken'),
        (201, 'Commercial Air Conditioner', 'Breakage / Damage', 'Jammed'),
        (202, 'Commercial Air Conditioner', 'Breakage / Damage', 'Horizontal vane not working'),
        (203, 'Commercial Air Conditioner', 'Breakage / Damage', 'Frozen Evaporator Coil'),
        (204, 'Commercial Air Conditioner', 'Sound / Noise', 'Humming'),
        (205, 'Commercial Air Conditioner', 'Sound / Noise', 'Knocking'),
        (206, 'Commercial Air Conditioner', 'Sound / Noise', 'Clicking'),
        (207, 'Commercial Air Conditioner', 'Sound / Noise', 'Buzzing'),
        (208, 'Commercial Air Conditioner', 'Sound / Noise', 'Compressor too loud'),
        (209, 'Commercial Air Conditioner', 'Sound / Noise', 'Squealing/High pitched sound'),
        (210, 'Commercial Air Conditioner', 'Sound / Noise', 'Line set'),
        (211, 'Commercial Air Conditioner', 'Sound / Noise', 'Unlisted (Specify in notes)'),
        (212, 'Commercial Air Conditioner', 'Sound / Noise', 'Rattling'),
        (213, 'Commercial Air Conditioner', 'Sound / Noise', 'Squealing'),
        (214, 'Commercial Air Conditioner', 'Sound / Noise', 'Indoor unit - Abnormal noise'),
        (215, 'Commercial Air Conditioner', 'Sound / Noise', 'Outdoor unit - Abnormal Noise'),
        (216, 'Commercial Air Conditioner', 'Operation', 'Adjusting temperature setting'),
        (217, 'Commercial Air Conditioner', 'Operation', 'Auto Mode'),
        (218, 'Commercial Air Conditioner', 'Operation', 'Cool Mode'),
        (219, 'Commercial Air Conditioner', 'Operation', 'Dehumidification Mode'),
        (220, 'Commercial Air Conditioner', 'Operation', 'Energy saver Mode'),
        (221, 'Commercial Air Conditioner', 'Operation', 'Fan Mode'),
        (222, 'Commercial Air Conditioner', 'Operation', 'Heat Mode'),
        (223, 'Commercial Air Conditioner', 'Operation', 'Remote Control'),
        (224, 'Commercial Air Conditioner', 'Operation', 'Sleep Mode'),
        (225, 'Commercial Air Conditioner', 'Operation', 'Timer'),
        (226, 'Commercial Air Conditioner', 'Operation', 'Fan runs all the time'),
        (227, 'Commercial Air Conditioner', 'Operation', 'Auto Restart'),
        (228, 'Commercial Air Conditioner', 'Operation', 'Outdoor fan cracked'),
        (229, 'Commercial Air Conditioner', 'Operation', 'Outdoor fan not moving'),
        (230, 'Commercial Air Conditioner', 'Operation', 'Does not Dehumidify'),
        (231, 'Commercial Air Conditioner', 'Operation', 'Heat from cabinet or Exhaust'),
        (232, 'Commercial Air Conditioner', 'Operation', 'Runs contantly or too much'),
        (233, 'Commercial Air Conditioner', 'Operation', 'Fan doesn\'t run'),
        (234, 'Commercial Air Conditioner', 'Operation', 'Mode'),
        (235, 'Commercial Air Conditioner', 'Settings', 'Fan speed'),
        (236, 'Commercial Air Conditioner', 'Settings', '2-4 way air deflection'),
        (237, 'Commercial Air Conditioner', 'Settings', 'Air purifier (PTAC)'),
        (238, 'Commercial Air Conditioner', 'Settings', 'Variable fan speeds'),
        (239, 'Commercial Air Conditioner', 'Settings', 'Heat pump doesn\'t engage'),
        (240, 'Commercial Air Conditioner', 'Settings', 'Indoor fan motor'),
        (241, 'Commercial Air Conditioner', 'CAC Leaking', 'Insufficient dehumidification'),
        (242, 'Commercial Air Conditioner', 'CAC Leaking', 'Outdoor coil leak'),
        (243, 'Commercial Air Conditioner', 'CAC Leaking', 'Refrigerant charge requirements'),
        (244, 'Commercial Air Conditioner', 'CAC Leaking', 'Pinging (water splashing)'),
        (245, 'Commercial Air Conditioner', 'CAC Leaking', 'Refrigerant - line set'),
        (246, 'Commercial Air Conditioner', 'CAC Leaking', 'Refrigerant - Service Valves'),
        (247, 'Commercial Air Conditioner', 'CAC Operation', 'Heat pump doesn\'t engage'),
        (248, 'Commercial Air Conditioner', 'CAC Operation', 'Indoor fan motor'),
        (249, 'Commercial Air Conditioner', 'CAC Operation', 'Ionizing Filter (PTAC)'),
        (250, 'Commercial Air Conditioner', 'Cooling', 'Air flow problem'),
        (251, 'Commercial Air Conditioner', 'Icing/Frost', 'Iced / Frosted behind front grille (Freezing up)'),
        (252, 'Commercial Air Conditioner', 'Icing/Frost', 'Iced / Frosted piping'),
        (253, 'Commercial Air Conditioner', 'Icing/Frost', 'Service valves/Line set'),
        (254, 'Refrigerator', 'Power', 'No power'),
        (255, 'Refrigerator', 'Cooling', 'Not cooling'),
        (256, 'Refrigerator', 'Cooling', 'Not cold enough'),
        (257, 'Refrigerator', 'Cooling', 'Condensation / Moisture / Water droplets between or around doors'),
        (258, 'Refrigerator', 'Cooling', 'Inside Refrigerator or Freezer'),
        (259, 'Refrigerator', 'Cooling', 'Too cold'),
        (260, 'Refrigerator', 'Frosting', 'Frost Buildup'),
        (261, 'Refrigerator', 'Door Issues', 'Doors wont close'),
        (262, 'Refrigerator', 'Door Issues', 'Doors Open too easily'),
        (263, 'Refrigerator', 'Door Issues', 'Doors hard to open'),
        (264, 'Refrigerator', 'Door Issues', 'Doors don\'t seal'),
        (265, 'Refrigerator', 'Door Issues', 'Doors Uneven'),
        (266, 'Refrigerator', 'Door Issues', 'DID issues'),
        (267, 'Refrigerator', 'Door Issues', 'Noise & Alarms'),
        (268, 'Refrigerator', 'Icemaker Issues', 'No Ice'),
        (269, 'Refrigerator', 'Icemaker Issues', 'Not enough Ice'),
        (270, 'Refrigerator', 'Icemaker Issues', 'Water overfilling tray'),
        (271, 'Refrigerator', 'Icemaker Issues', 'Ice overflowing the bin'),
        (272, 'Refrigerator', 'Icemaker Issues', 'Bad Taste'),
        (273, 'Refrigerator', 'Icemaker Issues', 'Particles in Ice'),
        (274, 'Refrigerator', 'Icemaker Issues', 'Tray will not turn upright'),
        (275, 'Refrigerator', 'Icemaker Issues', 'Cannot remove the bucket'),
        (276, 'Refrigerator', 'Icemaker Issues', 'Not enough ice storage capacity'),
        (277, 'Refrigerator', 'Dispenser Issue', 'Water doesn\'t dispense'),
        (278, 'Refrigerator', 'Dispenser Issue', 'Water is not cold from dispenser'),
        (279, 'Refrigerator', 'Dispenser Issue', 'Slow water Dispensing'),
        (280, 'Refrigerator', 'Dispenser Issue', 'Ice doesn\'t dispense'),
        (281, 'Refrigerator', 'Dispenser Issue', 'Set to cube but dispenses crushed'),
        (282, 'Refrigerator', 'Dispenser Issue', 'Odour  in Ice / Water'),
        (283, 'Refrigerator', 'Dispenser Issue', 'Dispenser Lights don\'t work'),
        (284, 'Refrigerator', 'Dispenser Issue', 'Controls don\'t work'),
        (285, 'Refrigerator', 'Dispenser Issue', 'Filter Indicators Will not Reset'),
        (286, 'Refrigerator', 'Dispenser Issue', 'Room Temperature display incorrect'),
        (287, 'Refrigerator', 'Dispenser Issue', 'Water / Ice Continuously dispense'),
        (288, 'Refrigerator', 'Dispenser Issue', 'From Back / Bottom / Front'),
        (289, 'Refrigerator', 'Leaking', 'From Dispenser'),
        (290, 'Refrigerator', 'Leaking', 'Inside Freezer (sheets of ice)'),
        (291, 'Refrigerator', 'Leaking', 'Inside Refrigerator'),
        (292, 'Refrigerator', 'Leaking', 'Clicking'),
        (293, 'Refrigerator', 'Noise', 'Humming'),
        (294, 'Refrigerator', 'Noise', 'Squeaking'),
        (295, 'Refrigerator', 'Noise', 'Vibrating'),
        (296, 'Refrigerator', 'Noise', 'Drilling'),
        (297, 'Refrigerator', 'Noise', 'Buzzing'),
        (298, 'Refrigerator', 'Noise', 'Other noises'),
        (299, 'Refrigerator', 'Noise', 'Cabinet Issues'),
        (300, 'Refrigerator', 'Other Issues', 'Control Panel Issues'),
        (301, 'Refrigerator', 'Other Issues', 'Door Seals'),
        (302, 'Refrigerator', 'Other Issues', 'Drawer not opening / closing'),
        (303, 'Refrigerator', 'Other Issues', 'Guide Rails'),
        (304, 'Refrigerator', 'Other Issues', 'Handles Loose'),
        (305, 'Refrigerator', 'Other Issues', 'Lighting Issues'),
        (306, 'Refrigerator', 'Other Issues', 'Liner Issues'),
        (307, 'Commercial Freezer', 'Power', 'No power'),
        (308, 'Commercial Freezer', 'Cooling', 'Not cooling'),
        (309, 'Commercial Freezer', 'Cooling', 'Not cold enough'),
        (310, 'Commercial Freezer', 'Cooling', 'Condensation / Moisture / Water droplets between or around doors'),
        (311, 'Commercial Freezer', 'Cooling', 'Inside Refrigerator or Freezer'),
        (312, 'Commercial Freezer', 'Cooling', 'Too cold'),
        (313, 'Commercial Freezer', 'Frosting', 'Frost Buildup'),
        (314, 'Commercial Freezer', 'Door Issues', 'Doors wont close'),
        (315, 'Commercial Freezer', 'Door Issues', 'Doors Open too easily'),
        (316, 'Commercial Freezer', 'Door Issues', 'Doors hard to open'),
        (317, 'Commercial Freezer', 'Door Issues', 'Doors don\'t seal'),
        (318, 'Commercial Freezer', 'Door Issues', 'Doors Uneven'),
        (319, 'Commercial Freezer', 'Door Issues', 'DID issues'),
        (320, 'Commercial Freezer', 'Door Issues', 'Noise & Alarms'),
        (321, 'Commercial Freezer', 'Icemaker Issues', 'No Ice'),
        (322, 'Commercial Freezer', 'Icemaker Issues', 'Not enough Ice'),
        (323, 'Commercial Freezer', 'Icemaker Issues', 'Water overfilling tray'),
        (324, 'Commercial Freezer', 'Icemaker Issues', 'Ice overflowing the bin'),
        (325, 'Commercial Freezer', 'Icemaker Issues', 'Bad Taste'),
        (326, 'Commercial Freezer', 'Icemaker Issues', 'Particles in Ice'),
        (327, 'Commercial Freezer', 'Icemaker Issues', 'Tray will not turn upright'),
        (328, 'Commercial Freezer', 'Icemaker Issues', 'Cannot remove the bucket'),
        (329, 'Commercial Freezer', 'Icemaker Issues', 'Not enough ice storage capacity'),
        (330, 'Commercial Freezer', 'Dispenser Issue', 'Water doesn\'t dispense'),
        (331, 'Commercial Freezer', 'Dispenser Issue', 'Water is not cold from dispenser'),
        (332, 'Commercial Freezer', 'Dispenser Issue', 'Slow water Dispensing'),
        (333, 'Commercial Freezer', 'Dispenser Issue', 'Ice doesn\'t dispense'),
        (334, 'Commercial Freezer', 'Dispenser Issue', 'Set to cube but dispenses crushed'),
        (335, 'Commercial Freezer', 'Dispenser Issue', 'Odour  in Ice / Water'),
        (336, 'Commercial Freezer', 'Dispenser Issue', 'Dispenser Lights don\'t work'),
        (337, 'Commercial Freezer', 'Dispenser Issue', 'Controls don\'t work'),
        (338, 'Commercial Freezer', 'Dispenser Issue', 'Filter Indicators Will not Reset'),
        (339, 'Commercial Freezer', 'Dispenser Issue', 'Room Temperature display incorrect'),
        (340, 'Commercial Freezer', 'Dispenser Issue', 'Water / Ice Continuously dispense'),
        (341, 'Commercial Freezer', 'Dispenser Issue', 'From Back / Bottom / Front'),
        (342, 'Commercial Freezer', 'Leaking', 'From Dispenser'),
        (343, 'Commercial Freezer', 'Leaking', 'Inside Freezer (sheets of ice)'),
        (344, 'Commercial Freezer', 'Leaking', 'Inside Refrigerator'),
        (345, 'Commercial Freezer', 'Leaking', 'Clicking'),
        (346, 'Commercial Freezer', 'Noise', 'Humming'),
        (347, 'Commercial Freezer', 'Noise', 'Squeaking'),
        (348, 'Commercial Freezer', 'Noise', 'Vibrating'),
        (349, 'Commercial Freezer', 'Noise', 'Drilling'),
        (350, 'Commercial Freezer', 'Noise', 'Buzzing'),
        (351, 'Commercial Freezer', 'Noise', 'Other noises'),
        (352, 'Commercial Freezer', 'Noise', 'Cabinet Issues'),
        (353, 'Commercial Freezer', 'Other Issues', 'Control Panel Issues'),
        (354, 'Commercial Freezer', 'Other Issues', 'Door Seals'),
        (355, 'Commercial Freezer', 'Other Issues', 'Drawer not opening / closing'),
        (356, 'Commercial Freezer', 'Other Issues', 'Guide Rails'),
        (357, 'Commercial Freezer', 'Other Issues', 'Handles Loose'),
        (358, 'Commercial Freezer', 'Other Issues', 'Lighting Issues'),
        (359, 'Commercial Freezer', 'Other Issues', 'Liner Issues'),
        (360, 'Microwave Oven', 'Power', 'No Power'),
        (361, 'Microwave Oven', 'Power', 'Powers On, won\'t Run'),
        (362, 'Microwave Oven', 'Power', 'Runs with Door open'),
        (363, 'Microwave Oven', 'Power', 'Runs on its own'),
        (364, 'Microwave Oven', 'Cooking', 'Not heating'),
        (365, 'Microwave Oven', 'Cooking', 'Uneven Cooking'),
        (366, 'Microwave Oven', 'Cooking', 'Overcooking (Food cooks too fast)'),
        (367, 'Microwave Oven', 'Cooking', 'Undercooking (Food cooks too slow)'),
        (368, 'Microwave Oven', 'Cooking', 'Improper Defrosting'),
        (369, 'Microwave Oven', 'Noises', 'Turntable Noises'),
        (370, 'Microwave Oven', 'Noises', 'Fan Noise'),
        (371, 'Microwave Oven', 'Noises', 'Other noises while cooking'),
        (372, 'Microwave Oven', 'Control Panel Issues', 'Keypad Bubbling (Air pockets)'),
        (373, 'Microwave Oven', 'Control Panel Issues', 'Keypad doesn\'t work'),
        (374, 'Microwave Oven', 'Control Panel Issues', 'Error Codes'),
        (375, 'Microwave Oven', 'Glass Tray Issues', 'Not moving'),
        (376, 'Microwave Oven', 'Glass Tray Issues', 'Broke During Operation'),
        (377, 'Microwave Oven', 'Glass Tray Issues', 'Rotating Ring Issue'),
        (378, 'OTG', 'Power', 'No Power'),
        (379, 'OTG', 'Power', 'Powers On, won\'t Run'),
        (380, 'OTG', 'Power', 'Runs with Door open'),
        (381, 'OTG', 'Power', 'Runs on its own'),
        (382, 'OTG', 'Cooking', 'Not heating'),
        (383, 'OTG', 'Cooking', 'Uneven Cooking'),
        (384, 'OTG', 'Cooking', 'Overcooking (Food cooks too fast)'),
        (385, 'OTG', 'Cooking', 'Undercooking (Food cooks too slow)'),
        (386, 'OTG', 'Cooking', 'Improper Defrosting'),
        (387, 'OTG', 'Noises', 'Turntable Noises'),
        (388, 'OTG', 'Noises', 'Fan Noise'),
        (389, 'OTG', 'Noises', 'Other noises while cooking'),
        (390, 'OTG', 'Control Panel Issues', 'Keypad Bubbling (Air pockets)'),
        (391, 'OTG', 'Control Panel Issues', 'Keypad doesn\'t work'),
        (392, 'OTG', 'Control Panel Issues', 'Error Codes'),
        (393, 'OTG', 'Glass Tray Issues', 'Not moving'),
        (394, 'OTG', 'Glass Tray Issues', 'Broke During Operation'),
        (395, 'OTG', 'Glass Tray Issues', 'Rotating Ring Issue'),
        (396, 'Dishwasher', 'Drying', 'Not drying'),
        (397, 'Dishwasher', 'Cleaning', 'White film and spots'),
        (398, 'Dishwasher', 'Cleaning', 'Not cleaning'),
        (399, 'Dishwasher', 'Draining', 'Not draining'),
        (400, 'Dishwasher', 'Noises', 'Humming'),
        (401, 'Dishwasher', 'Noises', 'Clicking'),
        (402, 'Dishwasher', 'Noises', 'Other'),
        (403, 'Dishwasher', 'Door Issues', 'Won\'t Close'),
        (404, 'Dishwasher', 'Door Issues', 'Leaks'),
        (405, 'Dishwasher', 'Leaks', 'Leaks'),
        (406, 'Dishwasher', 'Odor', 'Odor'),
        (407, 'Dishwasher', 'Dispenser Issues', 'Dispenser Issues'),
        (408, 'Dishwasher', 'Power', 'No Power'),
        (409, 'Dishwasher', 'Power', 'Powers On, won\'t Run'),
        (410, 'Dishwasher', 'Control Panel Issues', 'LEDs / Display do not light'),
        (411, 'Dishwasher', 'Control Panel Issues', 'Indicator Lights stay Lit or Flash'),
        (412, 'Dishwasher', 'Control Panel Issues', 'Buttons do not Respond'),
        (413, 'Dishwasher', 'Control Panel Issues', 'Error Code'),
        (414, 'Dishwasher', 'Water / Suds', 'No Water'),
        (415, 'Dishwasher', 'Water / Suds', 'Too Much Water'),
        (416, 'Dishwasher', 'Water / Suds', 'Too Many Suds'),
        (417, 'Dishwasher', 'Other Issues', 'Detergent / Rinse Aid'),
        (418, 'Dishwasher', 'Other Issues', 'Adjustable Tines & Rack Issues'),
        (419, 'Dishwasher', 'Other Issues', 'Long Wash Time'),
        (420, 'Dishwasher', 'Other Issues', 'Steam'),
        (421, 'Vacuum Cleaner', 'Operation', 'Auto Restart'),
        (422, 'Vacuum Cleaner', 'Operation', 'Fan Runs all the Time'),
        (423, 'Vacuum Cleaner', 'Operation', 'Outdoor fan cracked'),
        (424, 'Vacuum Cleaner', 'Operation', 'Outdoor fan not Moving'),
        (425, 'Vacuum Cleaner', 'Operation', 'Remote Control'),
        (426, 'Vacuum Cleaner', 'Operation', 'Does not Dehumidify'),
        (427, 'Vacuum Cleaner', 'Operation', 'Heat from Cabinet or Exhaust'),
        (428, 'Vacuum Cleaner', 'Operation', 'Runs Constantly or too much'),
        (429, 'Vacuum Cleaner', 'Operation', 'Fan doesn\'t run'),
        (430, 'Vacuum Cleaner', 'Leaking', 'Leaks from bucket'),
        (431, 'Vacuum Cleaner', 'Leaking', 'Leaks from drain hose connection'),
        (432, 'Vacuum Cleaner', 'Leaking', 'Misting (Smoking) from Air Vents'),
        (433, 'Vacuum Cleaner', 'Leaking', 'Spitting Water out of Front'),
        (434, 'Vacuum Cleaner', 'Leaking', 'Water Leaks from Unit'),
        (435, 'Vacuum Cleaner', 'Leaking', 'Condensation from IDU'),
        (436, 'Vacuum Cleaner', 'Leaking', 'Refrigerant - IDU coil'),
        (437, 'Vacuum Cleaner', 'Leaking', 'Refrigerant - line set'),
        (438, 'Vacuum Cleaner', 'Leaking', 'Refrigerant - ODU coil'),
        (439, 'Vacuum Cleaner', 'Leaking', 'Refrigerant - Service Valves'),
        (440, 'Vacuum Cleaner', 'Leaking', 'Smoking'),
        (441, 'Vacuum Cleaner', 'Settings', 'Mode'),
        (442, 'Vacuum Cleaner', 'Settings', 'Fan Speed'),
        (443, 'Vacuum Cleaner', 'Settings', '2-4 Way Air Deflection'),
        (444, 'Vacuum Cleaner', 'Settings', 'Air Purifier (PTAC)'),
        (445, 'Vacuum Cleaner', 'Settings', 'Timer'),
        (446, 'Vacuum Cleaner', 'Settings', 'Variable Fan Speeds'),
        (447, 'Vacuum Cleaner', 'Noise', 'Buzzing'),
        (448, 'Vacuum Cleaner', 'Noise', 'Clicking'),
        (449, 'Vacuum Cleaner', 'Noise', 'Humming'),
        (450, 'Vacuum Cleaner', 'Noise', 'Rattling'),
        (451, 'Vacuum Cleaner', 'Noise', 'Squealing'),
        (452, 'Vacuum Cleaner', 'Noise', 'High Pitched Sound'),
        (453, 'Vacuum Cleaner', 'Noise', 'Compressor Too Loud'),
        (454, 'Vacuum Cleaner', 'Noise', 'Knocking'),
        (455, 'Vacuum Cleaner', 'Noise', 'Line Set'),
        (456, 'Vacuum Cleaner', 'Noise', 'Other'),
        (457, 'Vacuum Cleaner', 'Power', 'Power Cord Reset Switch (AFCI)'),
        (458, 'Vacuum Cleaner', 'Power', 'Powers on and off abnormally'),
        (459, 'Vacuum Cleaner', 'Power', 'Powers on, Won\'t Run'),
        (460, 'Vacuum Cleaner', 'Power', 'Won\'t Power off'),
        (461, 'Vacuum Cleaner', 'Power', 'Won\'t Power on'),
        (462, 'Vacuum Cleaner', 'Power', 'Intermittent Power on / off'),
        (463, 'Vacuum Cleaner', 'Power', 'Intermittent Power'),
        (464, 'Vacuum Cleaner', 'Power', 'Power supply volts too high'),
        (465, 'Vacuum Cleaner', 'Power', 'Power supply volts too low'),
        (466, 'Vacuum Cleaner', 'Control Panel', 'Controls do not Respond'),
        (467, 'Vacuum Cleaner', 'Control Panel', 'Blinking Indicators or LEDs '),
        (468, 'Vacuum Cleaner', 'Control Panel', 'Display do not light'),
        (469, 'Vacuum Cleaner', 'Control Panel', 'Buttons do not Respond'),
        (470, 'Vacuum Cleaner', 'Icing / Frost', 'Iced / Frosted Behind Front Grille (Freezing up)'),
        (471, 'Vacuum Cleaner', 'Icing / Frost', 'Iced / Frosted Piping'),
        (472, 'Vacuum Cleaner', 'Icing / Frost', 'Service Valves / Line Set'),
        (473, 'Vacuum Cleaner', 'Temperature', 'Not Cooling'),
        (474, 'Vacuum Cleaner', 'Temperature', 'Not Heating'),
        (475, 'Vacuum Cleaner', 'Temperature', 'Temperature ajusts on its own'),
        (476, 'Vacuum Cleaner', 'Temperature', 'AI Mode'),
        (477, 'Vacuum Cleaner', 'Temperature', 'Insufficient Cooling'),
        (478, 'Vacuum Cleaner', 'Temperature', 'Insufficient Heating'),
        (479, 'Vacuum Cleaner', 'Temperature', 'Set Point Error'),
        (480, 'Vacuum Cleaner', 'CAC Leaking', 'Insufficient Dehumidification'),
        (481, 'Vacuum Cleaner', 'CAC Leaking', 'Outdoor Coil Leak'),
        (482, 'Vacuum Cleaner', 'CAC Leaking', 'Pinging (Water Splashing)'),
        (483, 'Vacuum Cleaner', 'CAC Operation', 'Heat pump does not engage'),
        (484, 'Vacuum Cleaner', 'CAC Operation', 'Indoor Fan Motor'),
        (485, 'Vacuum Cleaner', 'CAC Operation', 'Ionizing Filter (PTAC)'),
        (486, 'Washing Machine', 'Vibrations', 'Vibration'),
        (487, 'Washing Machine', 'Power Issues', 'No Power'),
        (488, 'Washing Machine', 'Power Issues', 'Powers on, Won\'t Run'),
        (489, 'Washing Machine', 'Power Issues', 'Powers on by itself'),
        (490, 'Washing Machine', 'Noises', 'Whirring / Air'),
        (491, 'Washing Machine', 'Noises', 'Knocking / Banging'),
        (492, 'Washing Machine', 'Noises', 'Squeaking'),
        (493, 'Washing Machine', 'Noises', 'Clicking'),
        (494, 'Washing Machine', 'Noises', 'Thumping'),
        (495, 'Washing Machine', 'Noises', 'Scraping '),
        (496, 'Washing Machine', 'Noises', 'Other Noises'),
        (497, 'Washing Machine', 'Odor / Buildup', 'Odor'),
        (498, 'Washing Machine', 'Leaking', 'Leaking'),
        (499, 'Washing Machine', 'Dispenser Issues', 'Water left in Dispenser'),
        (500, 'Washing Machine', 'Dispenser Issues', 'Does not dispense'),
        (501, 'Washing Machine', 'Dispenser Issues', 'Dispenser Stuck'),
        (502, 'Washing Machine', 'Control Panel Issues', 'Letters Rub Off'),
        (503, 'Washing Machine', 'Control Panel Issues', 'Time does not advance (Cycle sticks)'),
        (504, 'Washing Machine', 'Control Panel Issues', 'Condensation in Control Panel'),
        (505, 'Washing Machine', 'Control Panel Issues', 'LEDs or Display do not light'),
        (506, 'Washing Machine', 'Control Panel Issues', 'Indicator Lights stay lit or flash'),
        (507, 'Washing Machine', 'Control Panel Issues', 'Buttons Do not Respond'),
        (508, 'Washing Machine', 'Control Panel Issues', 'Error Code'),
        (509, 'Washing Machine', 'Control Panel Issues', 'Timer Sticks at 6 minutes'),
        (510, 'Washing Machine', 'Control Panel Issues', 'Timer sticks periodically during cycle'),
        (511, 'Washing Machine', 'Control Panel Issues', 'Timer does not advance (Cycle sticks)'),
        (512, 'Washing Machine', 'Water / Suds Issues', 'Not enough water'),
        (513, 'Washing Machine', 'Water / Suds Issues', 'Fills slow / Does not fill'),
        (514, 'Washing Machine', 'Water / Suds Issues', 'Too much water'),
        (515, 'Washing Machine', 'Water / Suds Issues', 'Does not drain / spin (Clothes too wet)'),
        (516, 'Washing Machine', 'Water / Suds Issues', 'Does not Rinse'),
        (517, 'Washing Machine', 'Water / Suds Issues', 'Not Enough Suds'),
        (518, 'Washing Machine', 'Water / Suds Issues', 'Too many Suds'),
        (519, 'Washing Machine', 'Water / Suds Issues', 'No Hot or Cold Water Supply'),
        (520, 'Washing Machine', 'Clothing Issues', 'Wrinkling'),
        (521, 'Washing Machine', 'Clothing Issues', 'Lint on Clothing'),
        (522, 'Washing Machine', 'Clothing Issues', 'Clothing not clean'),
        (523, 'Washing Machine', 'Clothing Issues', 'Clothing has odor'),
        (524, 'Washing Machine', 'Clothing Issues', 'Clothing torn / ripped'),
        (525, 'Washing Machine', 'Other Issues', 'Drum Issues'),
        (526, 'Washing Machine', 'Other Issues', 'Cabinet Issues'),
        (527, 'Washing Machine', 'Other Issues', 'Long Wash Time'),
        (528, 'Washing Machine', 'Other Issues', 'Long Spin Time'),
        (529, 'Washing Machine', 'Other Issues', 'Door Issues'),
        (530, 'Washing Machine', 'Other Issues', 'Steam'),
        (531, 'Washing Machine', 'Other Issues', 'RLM'),
        (532, 'Washing Machine', 'Combo Unit (Washer / Dryer)', 'Leaks from dispenser'),
        (533, 'Washing Machine', 'Combo Unit (Washer / Dryer)', 'Long Dry Time'),
        (534, 'Washing Machine', 'Combo Unit (Washer / Dryer)', 'Not Drying'),
        (535, 'Chimney', 'Odor', 'Bad Smell'),
        (536, 'Chimney', 'Body Damage', 'Body broken'),
        (537, 'Chimney', 'Body Damage', 'Body melted'),
        (538, 'Chimney', 'Body Damage', 'Color peel off'),
        (539, 'Chimney', 'Body Damage', 'Dented'),
        (540, 'Chimney', 'Body Damage', 'Glass broken'),
        (541, 'Chimney', 'Body Damage', 'Disbalance'),
        (542, 'Chimney', 'Operational', 'Jammed'),
        (543, 'Chimney', 'Operational', 'Does not Operate'),
        (544, 'Chimney', 'Operational', 'Some time stops'),
        (545, 'Chimney', 'Operational', 'Stops immediately'),
        (546, 'Chimney', 'Control Panel', 'Display not working'),
        (547, 'Chimney', 'Control Panel', 'Wrong parameters display'),
        (548, 'Chimney', 'Control Panel', 'Knob isssues'),
        (549, 'Chimney', 'Heating', 'Heating problem'),
        (550, 'Chimney', 'Wiring', 'Electric Shock'),
        (551, 'Chimney', 'Wiring', 'Wire Problem'),
        (552, 'Chimney', 'Noise', 'Abnormal Noises'),
        (553, 'Chimney', 'Leaking', 'Leakage'),
        (554, 'Hoods', 'Odor', 'Bad Smell'),
        (555, 'Hoods', 'Body Damage', 'Body broken'),
        (556, 'Hoods', 'Body Damage', 'Body melted'),
        (557, 'Hoods', 'Body Damage', 'Color peel off'),
        (558, 'Hoods', 'Body Damage', 'Dented'),
        (559, 'Hoods', 'Body Damage', 'Glass broken'),
        (560, 'Hoods', 'Body Damage', 'Disbalance'),
        (561, 'Hoods', 'Operational', 'Jammed'),
        (562, 'Hoods', 'Operational', 'Does not Operate'),
        (563, 'Hoods', 'Operational', 'Some time stops'),
        (564, 'Hoods', 'Operational', 'Stops immediately'),
        (565, 'Hoods', 'Control Panel', 'Display not working'),
        (566, 'Hoods', 'Control Panel', 'Wrong parameters display'),
        (567, 'Hoods', 'Control Panel', 'Knob isssues'),
        (568, 'Hoods', 'Heating', 'Heating problem'),
        (569, 'Hoods', 'Wiring', 'Electric Shock'),
        (570, 'Hoods', 'Wiring', 'Wire Problem'),
        (571, 'Hoods', 'Noise', 'Abnormal Noises'),
        (572, 'Hoods', 'Leaking', 'Leakage'),
        (573, 'Water Heater', 'Body Damage', 'Body broken'),
        (574, 'Water Heater', 'Body Damage', 'Stuck Valve'),
        (575, 'Water Heater', 'Body Damage', 'Bad Gasket'),
        (576, 'Water Heater', 'Water Flow', 'Slow Water Flow'),
        (577, 'Water Heater', 'Water Flow', 'Improper Water Pressure'),
        (578, 'Water Heater', 'Water Flow', 'Water Leak'),
        (579, 'Water Heater', 'Noise', 'Abnormal Noises'),
        (580, 'Water Heater', 'Operational', 'Does not Operate'),
        (581, 'Water Heater', 'Operational', 'Some time stops'),
        (582, 'Water Heater', 'Operational', 'Stops immediately'),
        (583, 'Water Heater', 'Operational', 'Faulty temperature and pressure (T&P) relief valve'),
        (584, 'Water Heater', 'Heating', 'Overheating'),
        (585, 'Water Heater', 'Heating', 'Loose heating element bolts'),
        (586, 'Water Heater', 'Wiring', 'Electric Shock'),
        (587, 'Water Heater', 'Wiring', 'Wire Problem'),
        (588, 'Water Heater', 'Control Panel', 'Display not working'),
        (589, 'Water Heater', 'Control Panel', 'Wrong parameters display'),
        (590, 'Water Heater', 'Control Panel', 'Knob isssues'),
        (591, 'Water Heater', 'Leaking', 'Leakage in Water Tank'),
        (592, 'Water Heater', 'Leaking', 'Leak from nearby plumbing connection'),
        (593, 'Electric Kettle', 'Body Damage', 'Body broken'),
        (594, 'Electric Kettle', 'Leaking', 'Water Leak'),
        (595, 'Electric Kettle', 'Operational', 'Does not Operate'),
        (596, 'Electric Kettle', 'Operational', 'Some time stops'),
        (597, 'Electric Kettle', 'Operational', 'Stops immediately'),
        (598, 'Electric Kettle', 'Operational', 'Switch Trips'),
        (599, 'Electric Kettle', 'Operational', 'Water does not heat'),
        (600, 'Electric Kettle', 'Wiring', 'Electric Shock'),
        (601, 'Electric Kettle', 'Wiring', 'Wire Problem'),
        (602, 'Electric Kettle', 'Power', 'No Power'),
        (603, 'Electric Kettle', 'Power', 'Powers on, Won\'t Run'),
        (604, 'Rice Cooker', 'Body Damage', 'Body broken'),
        (605, 'Rice Cooker', 'Operational', 'Does not Operate'),
        (606, 'Rice Cooker', 'Operational', 'Some time stops'),
        (607, 'Rice Cooker', 'Operational', 'Stops immediately'),
        (608, 'Rice Cooker', 'Operational', 'Switch Trips'),
        (609, 'Rice Cooker', 'Operational', 'Food is undercooked'),
        (610, 'Rice Cooker', 'Operational', 'Food is overcooked'),
        (611, 'Rice Cooker', 'Wiring', 'Electric Shock'),
        (612, 'Rice Cooker', 'Wiring', 'Wire Problem'),
        (613, 'Rice Cooker', 'Power', 'No Power'),
        (614, 'Rice Cooker', 'Power', 'Powers on, Won\'t Run'),
        (615, 'Air Cooler', 'Odor', 'Abnormal odour'),
        (616, 'Air Cooler', 'Operational', 'Does not operate'),
        (617, 'Air Cooler', 'Operational', 'Stopped working'),
        (618, 'Air Cooler', 'Operational', 'Improper Airflow'),
        (619, 'Air Cooler', 'Operational', 'Swing Not Functioning'),
        (620, 'Air Cooler', 'Operational', 'Not Oscillating'),
        (621, 'Air Cooler', 'Operational', 'Stops immediately'),
        (622, 'Air Cooler', 'Control Panel', 'Controls are not responsive'),
        (623, 'Air Cooler', 'Control Panel', 'Knob Issues'),
        (624, 'Air Cooler', 'Power', 'No Power'),
        (625, 'Air Cooler', 'Power', 'Powers on, Won\'t Run'),
        (626, 'Air Cooler', 'Power', 'Intermittent Power on / offs'),
        (627, 'Audio Players', 'Audio Issues', 'Audio Out of Sync'),
        (628, 'Audio Players', 'Audio Issues', 'No Audio'),
        (629, 'Audio Players', 'Audio Issues', 'Bad Audio Quality'),
        (630, 'Audio Players', 'Noise Issues', 'Clicking'),
        (631, 'Audio Players', 'Noise Issues', 'Knocking'),
        (632, 'Audio Players', 'Noise Issues', 'Grinding '),
        (633, 'Audio Players', 'Noise Issues', 'Humming'),
        (634, 'Audio Players', 'Power Issues', 'No Power / Boot Mode'),
        (635, 'Audio Players', 'Power Issues', 'Intermittent Power or Power On / Offs'),
        (636, 'Audio Players', 'Disc Playback Issues', 'Discs won\'t play'),
        (637, 'Audio Players', 'Disc Playback Issues', 'Playback Quality or Errors'),
        (638, 'Audio Players', 'Disc Playback Issues', 'Disc Stuck'),
        (639, 'Audio Players', 'Channels / Tuning', 'Channels / Tuning'),
        (640, 'Audio Players', 'Video Issues', 'Black & White Picture'),
        (641, 'Audio Players', 'Video Issues', 'Picture Size or Aspect Ratio'),
        (642, 'Audio Players', 'Video Issues', 'No Signal'),
        (643, 'Audio Players', 'Operational', 'Remote not working'),
        (644, 'Home Theatre', 'Audio', 'Audio Out of Sync'),
        (645, 'Home Theatre', 'Audio', 'No Audio from Speaker'),
        (646, 'Home Theatre', 'Audio', 'Bad Audio Quality'),
        (647, 'Home Theatre', 'Audio', 'Distorted Audio'),
        (648, 'Home Theatre', 'Audio', 'My Surround Speakers Aren?t Working'),
        (649, 'Home Theatre', 'Audio', 'My Front Speakers Don?t Sound Right'),
        (650, 'Home Theatre', 'Audio', 'My Height Speakers Don?t Sound Right'),
        (651, 'Home Theatre', 'Audio', 'There?s Static Coming From My Speakers'),
        (652, 'Home Theatre', 'Audio', 'The Entire System Sounds ?Off?'),
        (653, 'Home Theatre', 'Operational', 'Remote not working'),
        (654, 'Home Theatre', 'Noise Issues', 'Clicking'),
        (655, 'Home Theatre', 'Noise Issues', 'Knocking'),
        (656, 'Home Theatre', 'Noise Issues', 'Grinding '),
        (657, 'Home Theatre', 'Noise Issues', 'Humming'),
        (658, 'Home Theatre', 'Power Issues', 'No Power / Boot Mode'),
        (659, 'Home Theatre', 'Power Issues', 'Intermittent Power or Power On / Offs'),
        (660, 'Home Theatre', 'Disc Playback Issues', 'Discs won\'t play'),
        (661, 'Home Theatre', 'Disc Playback Issues', 'Playback Quality or Errors'),
        (662, 'Home Theatre', 'Disc Playback Issues', 'Disc Stuck'),
        (663, 'Home Theatre', 'Disc Playback Issues', 'BD Playback (Specific Titles)'),
        (664, 'Home Theatre', 'Channels / Tuning', 'Adding Chanels'),
        (665, 'Home Theatre', 'Channels / Tuning', 'Deleting Channels'),
        (666, 'Home Theatre', 'Video Issues', 'Black & White Picture'),
        (667, 'Home Theatre', 'Video Issues', 'Picture Size or Aspect Ratio'),
        (668, 'Home Theatre', 'Video Issues', 'No Signal'),
        (669, 'Home Theatre', 'Video Issues', '3D Playback or Performance'),
        (670, 'Home Theatre', 'Video Issues', 'Horizontal or Vertical Lines During Playback'),
        (671, 'Home Theatre', 'Video Issues', 'Invalid Format or Format Not supported'),
        (672, 'Home Theatre', 'Video Issues', 'Black Screen / No Image'),
        (673, 'Home Theatre', 'Video Issues', 'Poor Color'),
        (674, 'Home Theatre', 'Video Issues', 'Poor Picture Quality'),
        (675, 'Home Theatre', 'Video Issues', 'Poor Resolution'),
        (676, 'Home Theatre', 'Video Issues', 'Black Screen / No Image'),
        (677, 'Home Theatre', 'Video Issues', 'Poor Color'),
        (678, 'Home Theatre', 'Video Issues', 'Poor Picture Quality'),
        (679, 'Home Theatre', 'Video Issues', 'Poor Resolution'),
        (680, 'Speakers', 'Audio', 'Audio Out of Sync'),
        (681, 'Speakers', 'Audio', 'No Audio from Speaker'),
        (682, 'Speakers', 'Audio', 'Bad Audio Quality'),
        (683, 'Speakers', 'Audio', 'Distorted Audio'),
        (684, 'Speakers', 'Audio', 'My Surround Speakers Aren?t Working'),
        (685, 'Speakers', 'Audio', 'My Front Speakers Don?t Sound Right'),
        (686, 'Speakers', 'Audio', 'My Height Speakers Don?t Sound Right'),
        (687, 'Speakers', 'Audio', 'There?s Static Coming From My Speakers'),
        (688, 'Speakers', 'Audio', 'The Entire System Sounds ?Off?'),
        (689, 'Speakers', 'Operational', 'Remote not working'),
        (690, 'Speakers', 'Noise Issues', 'Clicking'),
        (691, 'Speakers', 'Noise Issues', 'Knocking'),
        (692, 'Speakers', 'Noise Issues', 'Grinding '),
        (693, 'Speakers', 'Noise Issues', 'Humming'),
        (694, 'Speakers', 'Power Issues', 'No Power / Boot Mode'),
        (695, 'Speakers', 'Power Issues', 'Intermittent Power or Power On / Offs'),
        (696, 'Speakers', 'Disc Playback Issues', 'Discs won\'t play'),
        (697, 'Speakers', 'Disc Playback Issues', 'Playback Quality or Errors'),
        (698, 'Speakers', 'Disc Playback Issues', 'Disc Stuck'),
        (699, 'Speakers', 'Disc Playback Issues', 'BD Playback (Specific Titles)'),
        (700, 'Speakers', 'Channels / Tuning', 'Adding Chanels'),
        (701, 'Speakers', 'Channels / Tuning', 'Deleting Channels'),
        (702, 'Speakers', 'Video Issues', 'Black & White Picture'),
        (703, 'Speakers', 'Video Issues', 'Picture Size or Aspect Ratio'),
        (704, 'Speakers', 'Video Issues', 'No Signal'),
        (705, 'Speakers', 'Video Issues', '3D Playback or Performance'),
        (706, 'Speakers', 'Video Issues', 'Horizontal or Vertical Lines During Playback'),
        (707, 'Speakers', 'Video Issues', 'Invalid Format or Format Not supported'),
        (708, 'Speakers', 'Video Issues', 'Black Screen / No Image'),
        (709, 'Speakers', 'Video Issues', 'Poor Color'),
        (710, 'Speakers', 'Video Issues', 'Poor Picture Quality'),
        (711, 'Speakers', 'Video Issues', 'Poor Resolution'),
        (712, 'Speakers', 'Video Issues', 'Black Screen / No Image'),
        (713, 'Speakers', 'Video Issues', 'Poor Color'),
        (714, 'Speakers', 'Video Issues', 'Poor Picture Quality'),
        (715, 'Speakers', 'Video Issues', 'Poor Resolution'),
        (716, 'Air Purifier', 'Odor', 'Abnormal odour'),
        (717, 'Air Purifier', 'Operational', 'Does not operate'),
        (718, 'Air Purifier', 'Operational', 'Stopped working'),
        (719, 'Air Purifier', 'Operational', 'Improper Airflow'),
        (720, 'Air Purifier', 'Operational', 'Some time stops'),
        (721, 'Air Purifier', 'Operational', 'Stops immediately'),
        (722, 'Air Purifier', 'Control Panel', 'Controls are not responsive'),
        (723, 'Air Purifier', 'Control Panel', 'Display not working'),
        (724, 'Air Purifier', 'Control Panel', 'Wrong parameters display'),
        (725, 'Room Heater', 'Noise', 'Abnormal noise'),
        (726, 'Room Heater', 'Operational', 'Does not operate'),
        (727, 'Room Heater', 'Operational', 'Stopped working'),
        (728, 'Room Heater', 'Operational', 'Improper Airflow'),
        (729, 'Room Heater', 'Operational', 'Some time stops'),
        (730, 'Room Heater', 'Operational', 'Stops immediately'),
        (731, 'Room Heater', 'Power', 'No power'),
        (732, 'Room Heater', 'Power', 'Powers on, Won\'t Work'),
        (733, 'Water Purifier', 'Purified Water', 'Abnormal water taste'),
        (734, 'Water Purifier', 'Purified Water', 'No purified water running out'),
        (735, 'Water Purifier', 'Purified Water', 'Discharging too much residential water'),
        (736, 'Water Purifier', 'Purified Water', 'Too little amount of hot water'),
        (737, 'Water Purifier', 'Purified Water', 'Lukewarm water'),
        (738, 'Water Purifier', 'Purified Water', 'No hot water activation'),
        (739, 'Water Purifier', 'Purified Water', 'No cold water activation'),
        (740, 'Water Purifier', 'Display', 'No power turned on'),
        (741, 'Water Purifier', 'Display', 'Icon representing filter change blinks/lightens'),
        (742, 'Water Purifier', 'Display', 'Inquiry about meaning of indicator such as filter'),
        (743, 'Water Purifier', 'Display', 'Display showing \'insufficient fluid\''),
        (744, 'Water Purifier', 'Display', 'No light on front indicator'),
        (745, 'Water Purifier', 'Display', 'Only level 1 or 2 temperature indicator works'),
        (746, 'Water Purifier', 'Display', 'Temperature lamp blinks or no lights'),
        (747, 'Water Purifier', 'Display', 'No light on purified lamp'),
        (748, 'Water Purifier', 'Leakage', 'Water leakage from main body'),
        (749, 'Water Purifier', 'Leakage', 'Water leakage from water supply hose'),
        (750, 'Water Purifier', 'Leakage', 'Water leakage due to no drainage'),
        (751, 'Water Purifier', 'Leakage', 'Water leakage to floor'),
        (752, 'Water Purifier', 'Leakage', 'Water leakage due to too much purified water'),
        (753, 'Water Purifier', 'Leakage', 'Water leakage from cork'),
        (754, 'Water Purifier', 'Leakage', 'Burst in hose'),
        (755, 'Water Purifier', 'Ionized water', 'feel sick after drinking alklai ionized water'),
        (756, 'Water Purifier', 'Ionized water', 'White floating particle in purified water'),
        (757, 'Water Purifier', 'Ionized water', 'Glittering floating particle or dark brown or black sediment in water'),
        (758, 'Water Purifier', 'Ionized water', 'Acidic water discharged'),
        (759, 'Water Purifier', 'Ionized water', 'Measuring ph level'),
        (760, 'Water Purifier', 'Ionized water', 'ph level not increasing'),
        (761, 'Water Purifier', 'Ionized water', 'Surface turns black when boiling water in aluminum kettle and pot'),
        (762, 'Water Purifier', 'Ionized water', 'White substance created when heated'),
        (763, 'Water Purifier', 'Ionized water', 'Strange taste or smell'),
        (764, 'Water Purifier', 'Noise', 'Noise (like woong)'),
        (765, 'Water Purifier', 'Noise', 'Noise (like shu)'),
        (766, 'Water Purifier', 'Noise', 'Noise (snapping)'),
        (767, 'Water Purifier', 'Noise', 'Noise (rattling)'),
        (768, 'Water Purifier', 'Power', 'No power turned on'),
        (769, 'Water Purifier', 'Power', 'Electrical breaker off'),
        (770, 'Water Purifier', 'Power', 'Electrical short on external of product'),
        (771, 'Water Purifier', 'Exterior', 'Scratch on external of product'),
        (772, 'Water Purifier', 'Exterior', 'Damaged components'),
        (773, 'Water Purifier', 'Exterior', 'High temperature of heat insulating board'),
        (774, 'Induction Cooktop', 'Power', 'The Induction Stovetop Lacks Power'),
        (775, 'Induction Cooktop', 'Power', 'Your Induction Cooktop Suddenly Turns Off Or Shuts Down'),
        (776, 'Induction Cooktop', 'Stove Burner', 'The Burner is Faulty'),
        (777, 'Induction Cooktop', 'Stove Burner', 'The Stove is in Lock Mode'),
        (778, 'Induction Cooktop', 'Heating', 'Overheating Or Uneven Heating'),
        (779, 'Induction Cooktop', 'Control Panel', 'The Touch Panel Buttons (Or The Entire Panel) Is Not Working'),
        (780, 'Induction Cooktop', 'Control Panel', 'LED Lights Keep On Blinking'),
        (781, 'Air Fryer', 'Food', 'My Food Is Too Soggy, Dry, or Chewy'),
        (782, 'Air Fryer', 'Food', 'My Food Remains Raw or Undercooked'),
        (783, 'Air Fryer', 'Food', 'My Food Isn?t Getting Crispy Enough'),
        (784, 'Air Fryer', 'Food', 'My Food Comes Out Wetter Than Normal'),
        (785, 'Air Fryer', 'Power', 'The Air Fryer Is On, but It Is Not Getting Any Power'),
        (786, 'Air Fryer', 'Power', 'My Air Fryer Does Not Turn On or Heat Up at All'),
        (787, 'Air Fryer', 'Exterior', 'Peeling Off Non Sticky Coating'),
        (788, 'Air Fryer', 'Exterior', 'Air Fryer Door Stop Closing'),
        (789, 'Air Fryer', 'Odor', 'My Air Fryer Smells Like Burning Plastic'),
        (790, 'Air Fryer', 'Odor', 'Air Fryer Toxic Odor'),
        (791, 'Air Fryer', 'Cooking', 'Air Fryer Releases White Smoke'),
        (792, 'Air Fryer', 'Cooking', 'The Exterior Is Browning Before the Interior Cooks'),
        (793, 'Oxy Fryer', 'Food', 'My Food Is Too Soggy, Dry, or Chewy'),
        (794, 'Oxy Fryer', 'Food', 'My Food Remains Raw or Undercooked'),
        (795, 'Oxy Fryer', 'Food', 'My Food Isn?t Getting Crispy Enough'),
        (796, 'Oxy Fryer', 'Food', 'My Food Comes Out Wetter Than Normal'),
        (797, 'Oxy Fryer', 'Power', 'The Oxy Fryer Is On, but It Is Not Getting Any Power'),
        (798, 'Oxy Fryer', 'Power', 'My Oxy Fryer Does Not Turn On or Heat Up at All'),
        (799, 'Oxy Fryer', 'Exterior', 'Peeling Off Non Sticky Coating'),
        (800, 'Oxy Fryer', 'Exterior', 'Oxy Fryer Door Stop Closing'),
        (801, 'Oxy Fryer', 'Odor', 'My Oxy Fryer Smells Like Burning Plastic'),
        (802, 'Oxy Fryer', 'Odor', 'Toxic Odor'),
        (803, 'Oxy Fryer', 'Cooking', 'Oxy Fryer Releases White Smoke'),
        (804, 'Oxy Fryer', 'Cooking', 'The Exterior Is Browning Before the Interior Cooks'),
        (805, 'Mixer Grinder', 'Power', 'No Power'),
        (806, 'Mixer Grinder', 'Power', 'Powers On, but doesn\'t function'),
        (807, 'Mixer Grinder', 'Switch', 'Mixer Grinder Overload Switch not working'),
        (808, 'Mixer Grinder', 'Switch', 'Auto Switch'),
        (809, 'Mixer Grinder', 'Switch', 'Reset Switch didn?t work'),
        (810, 'Mixer Grinder', 'Motor / Blades', 'Mixer Grinder keeps Tripping'),
        (811, 'Mixer Grinder', 'Motor / Blades', 'Mixer Grinder Stopped Working Suddenly'),
        (812, 'Mixer Grinder', 'Motor / Blades', 'Mixer Grinder Blade not Rotating'),
        (813, 'Mixer Grinder', 'Motor / Blades', 'Overload'),
        (814, 'Mixer Grinder', 'Motor / Blades', 'The blade is not freely moving'),
        (815, 'Mixer Grinder', 'Motor / Blades', 'Flat Feets'),
        (816, 'Mixer Grinder', 'Motor / Blades', 'Wire become Loose'),
        (817, 'Mixer Grinder', 'Motor / Blades', 'Mixer Grinder Overheating'),
        (818, 'Mixer Grinder', 'Leaking', 'Leakage from jar'),
        (819, 'Mixer Grinder', 'Breakage', 'Coupler is broken'),
        (820, 'Mixer Grinder', 'Breakage', 'Rubber gasket is torn'),
        (821, 'Mixer Grinder', 'Breakage', 'Lid is broken'),
        (822, 'Juicer Mixer Grinder', 'Power', 'No Power'),
        (823, 'Juicer Mixer Grinder', 'Power', 'Powers On, but doesn\'t function'),
        (824, 'Juicer Mixer Grinder', 'Switch', 'Mixer Grinder Overload Switch not working'),
        (825, 'Juicer Mixer Grinder', 'Switch', 'Auto Switch'),
        (826, 'Juicer Mixer Grinder', 'Switch', 'Reset Switch didn?t work'),
        (827, 'Juicer Mixer Grinder', 'Motor / Blades', 'Mixer Grinder keeps Tripping'),
        (828, 'Juicer Mixer Grinder', 'Motor / Blades', 'Mixer Grinder Stopped Working Suddenly'),
        (829, 'Juicer Mixer Grinder', 'Motor / Blades', 'Mixer Grinder Blade not Rotating'),
        (830, 'Juicer Mixer Grinder', 'Motor / Blades', 'Overload'),
        (831, 'Juicer Mixer Grinder', 'Motor / Blades', 'The blade is not freely moving'),
        (832, 'Juicer Mixer Grinder', 'Motor / Blades', 'Flat Feets'),
        (833, 'Juicer Mixer Grinder', 'Motor / Blades', 'Wire become Loose'),
        (834, 'Juicer Mixer Grinder', 'Motor / Blades', 'Mixer Grinder Overheating'),
        (835, 'Juicer Mixer Grinder', 'Leaking', 'Leakage from jar'),
        (836, 'Juicer Mixer Grinder', 'Breakage', 'Coupler is broken'),
        (837, 'Juicer Mixer Grinder', 'Breakage', 'Rubber gasket is torn'),
        (838, 'Juicer Mixer Grinder', 'Breakage', 'Lid is broken'),
        (839, 'Food Processor', 'Power', 'No Power'),
        (840, 'Food Processor', 'Power', 'Powers On, but doesn\'t function'),
        (841, 'Food Processor', 'Switch', 'Mixer Grinder Overload Switch not working'),
        (842, 'Food Processor', 'Switch', 'Auto Switch'),
        (843, 'Food Processor', 'Switch', 'Reset Switch didn?t work'),
        (844, 'Food Processor', 'Motor / Blades', 'Mixer Grinder keeps Tripping'),
        (845, 'Food Processor', 'Motor / Blades', 'Mixer Grinder Stopped Working Suddenly'),
        (846, 'Food Processor', 'Motor / Blades', 'Mixer Grinder Blade not Rotating'),
        (847, 'Food Processor', 'Motor / Blades', 'Overload'),
        (848, 'Food Processor', 'Motor / Blades', 'The blade is not freely moving'),
        (849, 'Food Processor', 'Motor / Blades', 'Flat Feets'),
        (850, 'Food Processor', 'Motor / Blades', 'Wire become Loose'),
        (851, 'Food Processor', 'Motor / Blades', 'Mixer Grinder Overheating'),
        (852, 'Food Processor', 'Leaking', 'Leakage from jar'),
        (853, 'Food Processor', 'Breakage', 'Coupler is broken'),
        (854, 'Food Processor', 'Breakage', 'Rubber gasket is torn'),
        (855, 'Food Processor', 'Breakage', 'Lid is broken'),
        (856, 'Wet Grinder', 'Power', 'No Power'),
        (857, 'Wet Grinder', 'Power', 'Powers On, but doesn\'t function'),
        (858, 'Wet Grinder', 'Switch', 'Mixer Grinder Overload Switch not working'),
        (859, 'Wet Grinder', 'Switch', 'Auto Switch'),
        (860, 'Wet Grinder', 'Switch', 'Reset Switch didn?t work'),
        (861, 'Wet Grinder', 'Motor / Blades', 'Mixer Grinder keeps Tripping'),
        (862, 'Wet Grinder', 'Motor / Blades', 'Mixer Grinder Stopped Working Suddenly'),
        (863, 'Wet Grinder', 'Motor / Blades', 'Mixer Grinder Blade not Rotating'),
        (864, 'Wet Grinder', 'Motor / Blades', 'Overload'),
        (865, 'Wet Grinder', 'Motor / Blades', 'The blade is not freely moving'),
        (866, 'Wet Grinder', 'Motor / Blades', 'Flat Feets'),
        (867, 'Wet Grinder', 'Motor / Blades', 'Wire become Loose'),
        (868, 'Wet Grinder', 'Motor / Blades', 'Mixer Grinder Overheating'),
        (869, 'Wet Grinder', 'Leaking', 'Leakage from jar'),
        (870, 'Wet Grinder', 'Breakage', 'Coupler is broken'),
        (871, 'Wet Grinder', 'Breakage', 'Rubber gasket is torn'),
        (872, 'Wet Grinder', 'Breakage', 'Lid is broken'),
        (873, 'Juicer', 'Power', 'No Power'),
        (874, 'Juicer', 'Power', 'Powers On, but doesn\'t function'),
        (875, 'Juicer', 'Switch', 'Mixer Grinder Overload Switch not working'),
        (876, 'Juicer', 'Switch', 'Auto Switch'),
        (877, 'Juicer', 'Switch', 'Reset Switch didn?t work'),
        (878, 'Juicer', 'Motor / Blades', 'Mixer Grinder keeps Tripping'),
        (879, 'Juicer', 'Motor / Blades', 'Mixer Grinder Stopped Working Suddenly'),
        (880, 'Juicer', 'Motor / Blades', 'Mixer Grinder Blade not Rotating'),
        (881, 'Juicer', 'Motor / Blades', 'Overload'),
        (882, 'Juicer', 'Motor / Blades', 'The blade is not freely moving'),
        (883, 'Juicer', 'Motor / Blades', 'Flat Feets'),
        (884, 'Juicer', 'Motor / Blades', 'Wire become Loose'),
        (885, 'Juicer', 'Motor / Blades', 'Mixer Grinder Overheating'),
        (886, 'Juicer', 'Leaking', 'Leakage from jar'),
        (887, 'Juicer', 'Breakage', 'Coupler is broken'),
        (888, 'Juicer', 'Breakage', 'Rubber gasket is torn'),
        (889, 'Juicer', 'Breakage', 'Lid is broken'),
        (890, 'Slow Juicer', 'Power', 'No Power'),
        (891, 'Slow Juicer', 'Power', 'Powers On, but doesn\'t function'),
        (892, 'Slow Juicer', 'Switch', 'Mixer Grinder Overload Switch not working'),
        (893, 'Slow Juicer', 'Switch', 'Auto Switch'),
        (894, 'Slow Juicer', 'Switch', 'Reset Switch didn?t work'),
        (895, 'Slow Juicer', 'Motor / Blades', 'Mixer Grinder keeps Tripping'),
        (896, 'Slow Juicer', 'Motor / Blades', 'Mixer Grinder Stopped Working Suddenly'),
        (897, 'Slow Juicer', 'Motor / Blades', 'Mixer Grinder Blade not Rotating'),
        (898, 'Slow Juicer', 'Motor / Blades', 'Overload'),
        (899, 'Slow Juicer', 'Motor / Blades', 'The blade is not freely moving'),
        (900, 'Slow Juicer', 'Motor / Blades', 'Flat Feets'),
        (901, 'Slow Juicer', 'Motor / Blades', 'Wire become Loose'),
        (902, 'Slow Juicer', 'Motor / Blades', 'Mixer Grinder Overheating'),
        (903, 'Slow Juicer', 'Leaking', 'Leakage from jar'),
        (904, 'Slow Juicer', 'Breakage', 'Coupler is broken'),
        (905, 'Slow Juicer', 'Breakage', 'Rubber gasket is torn'),
        (906, 'Slow Juicer', 'Breakage', 'Lid is broken'),
        (907, 'Toaster', 'Power', 'No Power'),
        (908, 'Toaster', 'Power', 'Powers On, but doesn\'t function'),
        (909, 'Toaster', 'Operational', 'Uneven Toasting'),
        (910, 'Toaster', 'Operational', 'Toasts are too hard'),
        (911, 'Toaster', 'Operational', 'Toasting stops after few seconds'),
        (912, 'Toaster', 'Operational', 'Sparking inside toasting slots'),
        (913, 'Toaster', 'Operational', 'Crumb tray jammed'),
        (914, 'Toaster', 'Operational', 'Lever doesn\'t stay down'),
        (915, 'Toaster', 'Operational', 'Does not pop'),
        (916, 'Toaster', 'Operational', 'Does not turn off automatically'),
        (917, 'Sandwich maker', 'Power', 'No Power'),
        (918, 'Sandwich maker', 'Power', 'Powers On, but doesn\'t function'),
        (919, 'Sandwich maker', 'Operational', 'Uneven Grilling'),
        (920, 'Sandwich maker', 'Operational', 'Sandwiches are too hard'),
        (921, 'Sandwich maker', 'Operational', 'Stops after few seconds'),
        (922, 'Sandwich maker', 'Operational', 'Does not turn off automatically'),
        (923, 'Sandwich maker', 'Operational', 'Sandwich sticks to heating plate'),
        (924, 'Sandwich maker', 'Cord', 'Melted cord'),
        (925, 'Sandwich maker', 'Cord', 'Torn Cord'),
        (926, 'Iron', 'Power', 'No Power'),
        (927, 'Iron', 'Power', 'Powers On, but doesn\'t function'),
        (928, 'Iron', 'Heating', 'Not heating at all'),
        (929, 'Iron', 'Heating', 'Not Heating Enough'),
        (930, 'Iron', 'Sticking', 'Iron sticking to fabric'),
        (931, 'Iron', 'Spotting', 'Spotting on fabric'),
        (932, 'Iron', 'Mineral Build Up', 'Mineral Build Up'),
        (933, 'Iron', 'Sole Plate Clogged', 'Sole Plate Clogged'),
        (934, 'Gas Stove', 'Burner', 'Surface Burner will not light'),
        (935, 'Gas Stove', 'Burner', 'Weak Burner Flame'),
        (936, 'Gas Stove', 'Burner', 'Oven Burner does not light'),
        (937, 'Gas Stove', 'Burner', 'Noisy Surface Burner Flame'),
        (938, 'Gas Stove', 'Burner', 'Broken Burner'),
        (939, 'Gas Stove', 'Exterior / Surface', 'Greasy Surface'),
        (940, 'Gas Stove', 'Exterior / Surface', 'Body Cracked'),
        (941, 'Gas Stove', 'Exterior / Surface', 'Broken Knobs'),
        (942, 'Gas Stove', 'Odor', 'Gas Odor'),
        (943, 'Freestanding Cooktop', 'Burner', 'Surface Burner will not light'),
        (944, 'Freestanding Cooktop', 'Burner', 'Weak Burner Flame'),
        (945, 'Freestanding Cooktop', 'Burner', 'Oven Burner does not light'),
        (946, 'Freestanding Cooktop', 'Burner', 'Noisy Surface Burner Flame'),
        (947, 'Freestanding Cooktop', 'Burner', 'Broken Burner'),
        (948, 'Freestanding Cooktop', 'Exterior / Surface', 'Greasy Surface'),
        (949, 'Freestanding Cooktop', 'Exterior / Surface', 'Body Cracked'),
        (950, 'Freestanding Cooktop', 'Exterior / Surface', 'Broken Knobs'),
        (951, 'Freestanding Cooktop', 'Odor', 'Gas Odor'),
        (952, 'Hobs', 'Burner', 'Surface Burner will not light'),
        (953, 'Hobs', 'Burner', 'Weak Burner Flame'),
        (954, 'Hobs', 'Burner', 'Oven Burner does not light'),
        (955, 'Hobs', 'Burner', 'Noisy Surface Burner Flame'),
        (956, 'Hobs', 'Burner', 'Broken Burner'),
        (957, 'Hobs', 'Exterior / Surface', 'Greasy Surface'),
        (958, 'Hobs', 'Exterior / Surface', 'Body Cracked'),
        (959, 'Hobs', 'Exterior / Surface', 'Broken Knobs'),
        (960, 'Hobs', 'Odor', 'Gas Odor'),
        (961, 'Gas Cooktop', 'Burner', 'Surface Burner will not light'),
        (962, 'Gas Cooktop', 'Burner', 'Weak Burner Flame'),
        (963, 'Gas Cooktop', 'Burner', 'Oven Burner does not light'),
        (964, 'Gas Cooktop', 'Burner', 'Noisy Surface Burner Flame'),
        (965, 'Gas Cooktop', 'Burner', 'Broken Burner'),
        (966, 'Gas Cooktop', 'Exterior / Surface', 'Greasy Surface'),
        (967, 'Gas Cooktop', 'Exterior / Surface', 'Body Cracked'),
        (968, 'Gas Cooktop', 'Exterior / Surface', 'Broken Knobs'),
        (969, 'Gas Cooktop', 'Odor', 'Gas Odor'),
        (970, 'Camera', 'Power', 'DSLR camera won\'t turn on'),
        (971, 'Camera', 'Battery', 'Camera battery error'),
        (972, 'Camera', 'Battery', 'Camera battery drains quickly'),
        (973, 'Camera', 'Photos / Videos', 'Picture has black or white spots'),
        (974, 'Camera', 'Photos / Videos', 'DSLR cannot save photos or video'),
        (975, 'Camera', 'LCD / Display', 'Camera LCD not working or blank'),
        (976, 'Camera', 'Focus', 'Camera won\'t focus'),
        (977, 'Camera', 'Focus', 'Poor autofocus'),
        (978, 'Camera', 'Error', 'Camera SD card error'),
        (979, 'Camera', 'Error', 'Camera shutter error'),
        (980, 'Camera', 'Error', 'Camera lens error'),
        (981, 'Camera', 'Memory Card', 'Camera microSD card photos and videos are missing'),
        (982, 'Camera', 'Damage', 'Wet camera'),
        (983, 'Camera', 'Damage', 'Broken Body'),
        (984, 'Camera', 'Damage', 'Broken Lens'),
        (985, 'Smartwearables', 'Battery / Charging', 'Battery Drain'),
        (986, 'Smartwearables', 'Battery / Charging', 'Not Charging'),
        (987, 'Smartwearables', 'Touchpad / Touch Screen', 'Touch Screen not working'),
        (988, 'Smartwearables', 'Touchpad / Touch Screen', 'Touch Screen Controls Lag'),
        (989, 'Smartwearables', 'Apps / Data', 'Installed Apps Not Showing Up'),
        (990, 'Smartwearables', 'Apps / Data', 'Notifications not coming through'),
        (991, 'Smartwearables', 'Apps / Data', ' Lost Data'),
        (992, 'Smartwearables', 'Connectivity', 'Bluetooth Not Working'),
        (993, 'Smartwearables', 'Connectivity', 'Won?t connect to phone'),
        (994, 'Smartwearables', 'Damage', 'Phycial damage'),
        (995, 'Smartwearables', 'Voice Controls', 'Sketchy Voice Control'),
        (996, 'Smartwearables', 'Voice Controls', 'Sync Issue'),
        (997, 'Headphones', 'Sound / Audio', 'No sound'),
        (998, 'Headphones', 'Sound / Audio', 'One Side Isn\'t working'),
        (999, 'Headphones', 'Sound / Audio', 'Poor Sound Quality'),
        (1000, 'Headphones', 'Sound / Audio', 'Mic not working'),
        (1001, 'Headphones', 'Connection', 'Connectivity Issue'),
        (1002, 'Headphones', 'Connection', 'Headphone jack not working'),
        (1003, 'Headphones', 'Connection', 'Bluetooth not connecting'),
        (1004, 'Earphones', 'Sound / Audio', 'No sound'),
        (1005, 'Earphones', 'Sound / Audio', 'One Side Isn\'t working'),
        (1006, 'Earphones', 'Sound / Audio', 'Poor Sound Quality'),
        (1007, 'Earphones', 'Sound / Audio', 'Mic not working'),
        (1008, 'Earphones', 'Connection', 'Connectivity Issue'),
        (1009, 'Earphones', 'Connection', 'Headphone jack not working'),
        (1010, 'Earphones', 'Connection', 'Bluetooth not connecting'),
        (1011, 'Earbuds', 'Sound / Audio', 'No sound'),
        (1012, 'Earbuds', 'Sound / Audio', 'One Side Isn\'t working'),
        (1013, 'Earbuds', 'Sound / Audio', 'Poor Sound Quality'),
        (1014, 'Earbuds', 'Sound / Audio', 'Mic not working'),
        (1015, 'Earbuds', 'Connection', 'Connectivity Issue'),
        (1016, 'Earbuds', 'Connection', 'Headphone jack not working'),
        (1017, 'Earbuds', 'Connection', 'Bluetooth not connecting'),
        (1018, 'Laptop', 'Troubleshooting - Audio', 'Audio out of sync'),
        (1019, 'Laptop', 'Troubleshooting - Audio', 'Low audio / Poor quality'),
        (1020, 'Laptop', 'Troubleshooting - Audio', 'No audio'),
        (1021, 'Laptop', 'Troubleshooting - Network connection', 'Bluetooth connection'),
        (1022, 'Laptop', 'Troubleshooting - Network connection', 'Wired network connection'),
        (1023, 'Laptop', 'Troubleshooting - Network connection', 'Wireless network connection'),
        (1024, 'Laptop', 'Troubleshooting - Noise', 'Fan noise'),
        (1025, 'Laptop', 'Troubleshooting - Hardware', 'Battery life'),
        (1026, 'Laptop', 'Troubleshooting - Hardware', 'Device overheats'),
        (1027, 'Laptop', 'Troubleshooting - Power', 'Intermittent power'),
        (1028, 'Laptop', 'Troubleshooting - Power', 'No power'),
        (1029, 'Laptop', 'Troubleshooting - Video', 'No video'),
        (1030, 'Laptop', 'Troubleshooting - Video', 'Picture quality and resolution'),
        (1031, 'Laptop', 'Troubleshooting - Windows', 'Backup & system recovery'),
        (1032, 'Laptop', 'Troubleshooting - Windows', 'Devices and printers'),
        (1033, 'Laptop', 'Troubleshooting - Windows', 'Software and Drivers'),
        (1034, 'Laptop', 'Troubleshooting - Windows', 'System crash'),
        (1035, 'Laptop', 'Troubleshooting - Windows', 'USB device connection'),
        (1036, 'Laptop', 'Troubleshooting - Windows', 'User Accounts'),
        (1037, 'Smartphone', 'Bluetooth', 'Headset'),
        (1038, 'Smartphone', 'Accessibility', 'Vision impaired support'),
        (1039, 'Smartphone', 'Accessibility', 'Hearing impaired support'),
        (1040, 'Smartphone', 'Accessibility', 'Physical limitation support'),
        (1041, 'Smartphone', 'Accessibility', 'Cognitive impairment support'),
        (1042, 'Smartphone', 'Accessibility', 'Setting'),
        (1043, 'Smartphone', 'Email/Accounts', 'Attachments'),
        (1044, 'Smartphone', 'Email/Accounts', 'Alerts/Notification'),
        (1045, 'Smartphone', 'Email/Accounts', 'Remove account'),
        (1046, 'Smartphone', 'Email/Accounts', 'Add & setup account'),
        (1047, 'Smartphone', 'Messaging', 'MMS (Picture/Video)'),
        (1048, 'Smartphone', 'Messaging', 'SMS'),
        (1049, 'Smartphone', 'Messaging', 'Voicemail'),
        (1050, 'Smartphone', 'Applications', 'Downloaded apps'),
        (1051, 'Smartphone', 'Applications', 'Preinstall apps'),
        (1052, 'Smartphone', 'Accessories', 'SIM card'),
        (1053, 'Smartphone', 'Accessories', 'Battery'),
        (1054, 'Smartphone', 'Accessories', 'USB Cable/Charger'),
        (1055, 'Smartphone', 'Camera', 'Camera'),
        (1056, 'Smartphone', 'Camera', 'Video'),
        (1057, 'Smartphone', 'Connectivity', 'Data/Internet connection'),
        (1058, 'Smartphone', 'Connectivity', 'Bluetooth'),
        (1059, 'Smartphone', 'Connectivity', 'USB'),
        (1060, 'Smartphone', 'Connectivity', 'Tethering & WIFI sharing/Hotspot'),
        (1061, 'Smartphone', 'Connectivity', 'HDMI'),
        (1062, 'Smartphone', 'Connectivity', 'File/media transfer (pictures, music, etc)'),
        (1063, 'Smartphone', 'Connectivity', 'DLNA'),
        (1064, 'Smartphone', 'Connectivity', 'GPS'),
        (1065, 'Smartphone', 'Connectivity', 'Wifi'),
        (1066, 'Smartphone', 'Connectivity', 'NFC'),
        (1067, 'Smartphone', 'Connectivity', 'Mobile network'),
        (1068, 'Smartphone', 'Contacts/Calender', 'Adding/Editing'),
        (1069, 'Smartphone', 'Contacts/Calender', 'Display options'),
        (1070, 'Smartphone', 'Contacts/Calender', 'Sync / Backup'),
        (1071, 'Smartphone', 'Keys/ Buttons', 'On-screen'),
        (1072, 'Smartphone', 'Keys/ Buttons', 'Physical'),
        (1073, 'Smartphone', 'Display', 'Settins'),
        (1074, 'Smartphone', 'Display', 'Screen'),
        (1075, 'Smartphone', 'Display', 'Lock/unlock screen'),
        (1076, 'Smartphone', 'Other issues', 'Activation'),
        (1077, 'Smartphone', 'Other issues', 'Calling features'),
        (1078, 'Smartphone', 'Other issues', 'Physical damage'),
        (1079, 'Smartphone', 'Other issues', 'Software updates'),
        (1080, 'Smartphone', 'Memory', 'Memory management'),
        (1081, 'Smartphone', 'Memory', 'File/media transfer (pictures, music, etc)'),
        (1082, 'Smartphone', 'Memory', 'Memory card'),
        (1083, 'Smartphone', 'Power', 'Battery life'),
        (1084, 'Smartphone', 'Power', 'Phone will not power on'),
        (1085, 'Smartphone', 'Power', 'Charging'),
        (1086, 'Smartphone', 'Power', 'Overheating'),
        (1087, 'Smartphone', 'Power', 'Power on/off'),
        (1088, 'Smartphone', 'Alerts/Sounds', 'Headset'),
        (1089, 'Smartphone', 'Alerts/Sounds', 'Microphone'),
        (1090, 'Smartphone', 'Alerts/Sounds', 'Speaker/Receiver'),
        (1091, 'Smartphone', 'Alerts/Sounds', 'Call log'),
        (1092, 'Smartphone', 'Alerts/Sounds', 'Vibrate'),
        (1093, 'Smartphone', 'Alerts/Sounds', 'Ringtone'),
        (1094, 'Feature Phone', 'Accessibility', 'Vision impaired support'),
        (1095, 'Feature Phone', 'Accessibility', 'Hearing impaired support'),
        (1096, 'Feature Phone', 'Accessibility', 'Physical limitation support'),
        (1097, 'Feature Phone', 'Accessibility', 'Cognitive impairment support'),
        (1098, 'Feature Phone', 'Accessibility', 'Setting'),
        (1099, 'Feature Phone', 'Email/Accounts', 'Attachments'),
        (1100, 'Feature Phone', 'Email/Accounts', 'Alerts/Notification'),
        (1101, 'Feature Phone', 'Email/Accounts', 'Remove account'),
        (1102, 'Feature Phone', 'Email/Accounts', 'Add & setup account'),
        (1103, 'Feature Phone', 'Messaging', 'MMS (Picture/Video)'),
        (1104, 'Feature Phone', 'Messaging', 'SMS'),
        (1105, 'Feature Phone', 'Messaging', 'Voicemail'),
        (1106, 'Feature Phone', 'Applications', 'Downloaded apps'),
        (1107, 'Feature Phone', 'Applications', 'Preinstall apps'),
        (1108, 'Feature Phone', 'Accessories', 'SIM card'),
        (1109, 'Feature Phone', 'Accessories', 'Battery'),
        (1110, 'Feature Phone', 'Accessories', 'USB Cable/Charger'),
        (1111, 'Feature Phone', 'Camera', 'Camera'),
        (1112, 'Feature Phone', 'Camera', 'Video'),
        (1113, 'Feature Phone', 'Connectivity', 'Data/Internet connection'),
        (1114, 'Feature Phone', 'Connectivity', 'Bluetooth'),
        (1115, 'Feature Phone', 'Connectivity', 'USB'),
        (1116, 'Feature Phone', 'Connectivity', 'Tethering & Wifi sharing/Hotspot'),
        (1117, 'Feature Phone', 'Connectivity', 'HDMI'),
        (1118, 'Feature Phone', 'Connectivity', 'File/media transfer (pictures, music, etc)'),
        (1119, 'Feature Phone', 'Connectivity', 'DLNA'),
        (1120, 'Feature Phone', 'Connectivity', 'GPS'),
        (1121, 'Feature Phone', 'Connectivity', 'Wifi'),
        (1122, 'Feature Phone', 'Connectivity', 'NFC'),
        (1123, 'Feature Phone', 'Connectivity', 'Mobile network'),
        (1124, 'Feature Phone', 'Contacts/Calender', 'Adding/Editing'),
        (1125, 'Feature Phone', 'Contacts/Calender', 'Display options'),
        (1126, 'Feature Phone', 'Contacts/Calender', 'Sync / Backup'),
        (1127, 'Feature Phone', 'Keys/ Buttons', 'On-screen'),
        (1128, 'Feature Phone', 'Keys/ Buttons', 'Physical'),
        (1129, 'Feature Phone', 'Display', 'Settings'),
        (1130, 'Feature Phone', 'Display', 'Screen'),
        (1131, 'Feature Phone', 'Display', 'Lock/unlock screen'),
        (1132, 'Feature Phone', 'Other issues', 'Activation'),
        (1133, 'Feature Phone', 'Other issues', 'Calling features'),
        (1134, 'Feature Phone', 'Other issues', 'Physical damage'),
        (1135, 'Feature Phone', 'Other issues', 'Software updates'),
        (1136, 'Feature Phone', 'Memory', 'Memory management'),
        (1137, 'Feature Phone', 'Memory', 'File/media transfer (pictures, music, etc)'),
        (1138, 'Feature Phone', 'Memory', 'Memory card'),
        (1139, 'Feature Phone', 'Power', 'Battery life'),
        (1140, 'Feature Phone', 'Power', 'Phone will not power on'),
        (1141, 'Feature Phone', 'Power', 'Charging'),
        (1142, 'Feature Phone', 'Power', 'Overheating'),
        (1143, 'Feature Phone', 'Power', 'Power on/off'),
        (1144, 'Feature Phone', 'Alerts/Sounds', 'Headset'),
        (1145, 'Feature Phone', 'Alerts/Sounds', 'Microphone'),
        (1146, 'Feature Phone', 'Alerts/Sounds', 'Speaker/Receiver'),
        (1147, 'Feature Phone', 'Alerts/Sounds', 'Ringtone'),
        (1148, 'Feature Phone', 'Alerts/Sounds', 'Vibrate'),
        (1149, 'Tablet', 'Power / Charging', 'My tablet is plugged in but it?s not charging'),
        (1150, 'Tablet', 'Power / Charging', 'Poor Battery Life'),
        (1151, 'Tablet', 'Power / Charging', 'Overheating'),
        (1152, 'Tablet', 'Damage', 'Cracked Screen  '),
        (1153, 'Tablet', 'Damage', 'Immersion in Water'),
        (1154, 'Tablet', 'Apps', 'My apps are constantly crashing'),
        (1155, 'Tablet', 'Apps', 'Apps not downloading'),
        (1156, 'Tablet', 'Connection', 'Connecting problem with Bluetooth'),
        (1157, 'Tablet', 'Connection', 'Connecting problem with cellular network'),
        (1158, 'Tablet', 'Connection', 'I can?t access my WiFi'),
        (1159, 'Tablet', 'Performance', 'My screen is frozen'),
        (1160, 'Tablet', 'Performance', 'My tablet is running slower than it usually does'),
        (1161, 'Tablet', 'Performance', 'MicroSD Card Not Working On Your Smartphone')");
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('product_issues');
    }
}
