<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateProductIconsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('product_icons', function (Blueprint $table) {
            $table->id();
            $table->string('category');
            $table->string('icon')->default('');
            $table->timestamp('created_at')->default(DB::raw('CURRENT_TIMESTAMP'));
            $table->timestamp('updated_at')->default(DB::raw('CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP'));
        });

        DB::statement("INSERT INTO `product_icons` (`id`, `category`, `icon`) VALUES
        (1, 'AC Accessories', 'AC.jpg'),
        (2, 'Audio', 'Headphone.jpg'),
        (3, 'Commercial TV', 'TV.jpg'),
        (4, 'Digital Signage', ''),
        (5, 'Dishwashers', 'Dishwasher.jpg'),
        (6, 'Ducted AC', 'AC.jpg'),
        (7, 'Floor Standing AC', 'AC.jpg'),
        (8, 'HRV', ''),
        (9, 'LCD Monitors', 'Monitor.jpg'),
        (10, 'Laptops', 'Laptop.jpg'),
        (11, 'Microwave Ovens', 'Microwave Oven.jpg'),
        (12, 'Mobile Accessories', 'Smart Phone.jpg'),
        (13, 'Mobile Phones', 'Smart Phone.jpg'),
        (14, 'Refrigerators', 'Refrigerator.jpg'),
        (15, 'Vacumm Cleaner', 'Vacuum Cleaner.jpg'),
        (16, 'Water Purifier', 'Water Purifier.jpg'),
        (17, 'Split AC', 'AC.jpg'),
        (18, 'TV', 'TV.jpg'),
        (19, 'Washing Machines', 'Washing Machine.jpg'),
        (20, 'Window AC', 'AC.jpg'),
        (21, 'Monitors', 'Monitor.jpg'),
        (22, 'Media Players', 'Headphone.jpg'),
        (23, 'Digital Photoframe', ''),
        (24, 'Headphones', 'Headphone.jpg'),
        (25, 'Soundbars', 'AMBEO Soundbar.jpg'),
        (26, 'Wireless Speakers', 'Bluetooth speaker.jpg'),
        (27, 'Home Audio', 'Home Theatre.jpg'),
        (28, 'Portable Audio', 'Bluetooth speaker.jpg'),
        (29, 'Mobile & Tablets', 'Tablet.jpg'),
        (30, 'Landline Phones', ''),
        (31, 'Cables & Connectivity', ''),
        (32, 'Batteries & Flashlights', ''),
        (33, 'Audio & Video Accessories', ''),
        (34, 'Computer Accessories', 'Monitor.jpg'),
        (35, 'Power Solutions', 'Power Bank.jpg'),
        (36, 'Care & Cleaning', ''),
        (37, 'Storage', ''),
        (38, 'Face Shavers', 'Trimmer.jpg'),
        (39, 'OneBlade - Trim, edge & shave', 'Trimmer.jpg'),
        (40, 'FACE Stylers & Grooming Kits', 'Trimmer.jpg'),
        (41, 'HAIR Clippers', ''),
        (42, 'BODY Groomers', 'Trimmer.jpg'),
        (43, 'FACE Skin', 'Trimmer.jpg'),
        (44, 'Accessories & Replacements', ''),
        (45, 'Hair Removal', 'Trimmer.jpg'),
        (46, 'Hair Care', 'Hair Dryer.jpg'),
        (47, 'Electric Toothbrushes', ''),
        (48, 'Toothbrush Heads', ''),
        (49, 'Philips Sonicare Airfloss', ''),
        (50, 'Active Living', ''),
        (51, 'Pain Relief', ''),
        (52, 'Pacifiers', ''),
        (53, 'Breast Pumps & Care', ''),
        (54, 'Baby Bottles & Nipples', ''),
        (55, 'Bottle Warmers & Sterilizers', ''),
        (56, 'Toddler Sippy Cups', ''),
        (57, 'Foodmakers & Tableware', 'Food Processor.jpg'),
        (58, 'Starter & Baby Gift Sets', ''),
        (59, 'Coffee', 'Coffee Maker.jpg'),
        (60, 'Kettles', 'Electric Kettle.jpg'),
        (61, 'Cooking', 'Food Processor.jpg'),
        (62, 'Cooking Accessories', 'Food Processor.jpg'),
        (63, 'Food Preparation', 'Food Processor.jpg'),
        (64, 'Vacuum Cleaners', 'Vacuum Cleaner.jpg'),
        (65, 'Ironing', 'Iron.jpg'),
        (66, 'Air Purifiers & Air Humidifiers', ''),
        (67, 'Water Drinking Solutions', 'Water Purifier.jpg'),
        (68, 'Choose a Fixture', ''),
        (69, 'Moodlighting', ''),
        (70, 'Disney', ''),
        (71, 'Hue', ''),
        (72, 'Choose a Bulb', ''),
        (73, 'Hearing Solutions', ''),
        (74, 'Car Lights', ''),
        (75, 'Motorcycle Lights', ''),
        (76, 'Car Air Qiuality', ''),
        (77, 'Men\'s Shaving & Grooming Accessories', 'Trimmer.jpg'),
        (78, 'Mother & Child Care', ''),
        (79, 'Household Accessories', ''),
        (80, 'Coffee Appliances Accessories & Parts', 'Coffee Maker.jpg'),
        (81, 'Residential', 'AC.jpg'),
        (82, 'Commercial', 'AC.jpg'),
        (83, 'Industrial', 'AC.jpg'),
        (84, 'Cold Chain Solution', 'AC.jpg'),
        (85, 'Televisions & Home Cinema', 'TV.jpg'),
        (86, 'Home Theatre & Soundbars', 'Home Theatre.jpg'),
        (87, 'Blu-ray Disc? & DVD Players', ''),
        (88, 'In Car', ''),
        (89, 'Storage & Cables', ''),
        (90, 'Video Cameras', 'Camera.jpg'),
        (91, 'PlayStation', ''),
        (92, 'Cameras', 'Camera.jpg'),
        (93, 'Microwave Oven', 'Microwave Oven.jpg'),
        (94, 'Washing Machine', 'Washing Machine.jpg'),
        (95, 'Clothes Dryer', ''),
        (96, 'AC', 'AC.jpg'),
        (97, 'Air Coolers', 'Air Cooler.jpg'),
        (98, 'Airtek Air Coolers', 'Air Cooler.jpg'),
        (99, 'Delonghi Group', ''),
        (100, 'Fan', 'Ceiling Fan.jpg'),
        (101, 'Healthcare Appliances', ''),
        (102, 'Heating Solutions', ''),
        (103, 'Irons', 'Iron.jpg'),
        (104, 'Kitchen Solutions', 'Chimney.jpg'),
        (105, 'Lighting', ''),
        (106, 'Miscellaneous Appliances', ''),
        (107, 'Switchgear', ''),
        (108, 'Mixer Grinder', 'Mixer Grinder.jpg'),
        (109, 'Juicer Mixer Grinder', 'Mixer Grinder.jpg'),
        (110, 'Food Processor', 'Food Processor.jpg'),
        (111, 'Hand Blender', 'Hand Blender.jpg'),
        (112, 'Chopper', ''),
        (113, 'OTG', 'OTG.jpg'),
        (114, 'Induction Cooker', 'Induction Cooktop.jpg'),
        (115, 'Pop up Toaster', 'Toaster.jpg'),
        (116, 'Sandwich Maker', 'Sandwich Maker.jpg'),
        (117, 'Coffee Maker', 'Coffee Maker.jpg'),
        (118, 'Juicer', 'Cold press juicer.jpg'),
        (119, 'Electric Kettles', 'Electric Kettle.jpg'),
        (120, 'Electric Tea Maker', 'Coffee Maker.jpg'),
        (121, 'Electric Iron', 'Iron.jpg'),
        (122, 'Water Heater', 'Geyser.jpg'),
        (123, 'Room Heater', 'Room Heater.jpg'),
        (124, 'Hair Dryer', 'Hair Dryer.jpg'),
        (125, 'Dry Masala Grinder', 'Mixer Grinder.jpg'),
        (126, 'Wet Grinder', 'Mixer Grinder.jpg'),
        (127, 'Grain Grinder', 'Mixer Grinder.jpg'),
        (128, 'Electric Chopper', ''),
        (129, 'Roti Maker', 'Roti Maker.jpg'),
        (130, 'Electric Kettle', 'Electric Kettle.jpg'),
        (131, 'Induction Cooktop', 'Induction Cooktop.jpg'),
        (132, 'Chimney', 'Chimney.jpg'),
        (133, 'Electric Rice Cooker', 'Rice Cooker.jpg'),
        (134, 'Multi Cooker', 'Rice Cooker.jpg'),
        (135, 'Air Fryer', ''),
        (136, 'Barbecue', 'BBQ.jpg'),
        (137, 'Electric Griller', ''),
        (138, 'Iron', 'Iron.jpg'),
        (139, 'Pressure Cooker', 'Pressure Cooker.jpg'),
        (140, 'Pressure Cooker Gaskets', 'Pressure Cooker.jpg'),
        (141, 'Non Stick Cookware', 'Frying Pan.jpg'),
        (142, 'Gas Stove', 'Gas Stove.jpg'),
        (143, 'Cleaning Solutions (Electric)', 'Vacuum Cleaner.jpg'),
        (144, 'Cleaning Solutions (Non-Electric)', 'Vacuum Cleaner.jpg'),
        (145, 'Tools and Accessories', ''),
        (146, 'Mobile', 'Smart Phone.jpg'),
        (147, 'Smartwearables/ Watches (Redmi/ MI)', 'Smart Wearable.jpg'),
        (148, 'Speakers', 'Speaker.jpg'),
        (149, 'Power Bank ( Redmi/ MI)', 'Power Bank.jpg'),
        (150, 'Vacuum Cleaner', 'Vacuum Cleaner.jpg'),
        (151, 'LED Bulbs', 'LED Bulb.jpg'),
        (152, 'Security Camera', 'Security Camera.jpg'),
        (153, 'Router', 'WiFi Router.jpg'),
        (154, 'Sunglasses', 'Sunglass.jpg'),
        (155, 'Shoes', ''),
        (156, 'Trimmer', 'Trimmer.jpg'),
        (157, 'Smartwearable', 'Smart Wearable.jpg'),
        (158, 'Power Bank', 'Power Bank.jpg'),
        (159, 'Earphones', 'Earphone.jpg'),
        (160, 'Fans', 'Ceiling Fan.jpg'),
        (161, 'Cooking Solutions', 'Microwave Oven.jpg'),
        (162, 'Fabric Care', 'Garment Steamer.jpg'),
        (163, 'Headphones & Earbuds', 'Headphone.jpg'),
        (164, 'Audio Sunglasses', 'Sunglass.jpg'),
        (165, 'Health', ''),
        (166, 'Appliances', ''),
        (167, 'Appliances - Platini Range', ''),
        (168, 'Pumps & Generators', ''),
        (169, 'Morphy Richards', ''),
        (170, 'Refrigerator - Single Door', 'Refrigerator.jpg'),
        (171, 'Refrigerator - Multi Door', 'Refrigerator.jpg'),
        (172, 'Dishwasher', 'Dishwasher.jpg'),
        (173, 'Microwave', 'Microwave Oven.jpg'),
        (174, 'Chest Freezer', ''),
        (175, 'Air Purifier', ''),
        (176, 'Built In', ''),
        (177, 'Small Domestic Appliances', ''),
        (178, 'Refrigerator', 'Refrigerator.jpg'),
        (179, 'Freezer', 'Refrigerator.jpg'),
        (180, 'Drum Washing Machine', 'Washing Machine.jpg'),
        (181, 'Home AC', 'AC.jpg'),
        (182, 'Commercial AC', 'AC.jpg'),
        (183, 'Medical Freeze', 'Refrigerator.jpg'),
        (184, 'Air Conditioner', 'AC.jpg'),
        (185, 'AirDresser', ''),
        (186, 'Tablets', 'Tablet.jpg'),
        (187, 'Speaker', 'Speaker.jpg'),
        (188, 'External HD', 'External HD.jpg'),
        (189, 'Juicer Mixer Grinders', 'Mixer Grinder.jpg'),
        (190, 'Blenders/Choppers', 'Hand Blender.jpg'),
        (191, 'Pop-Up Toasters', 'Toaster.jpg'),
        (192, 'Air Purifiers', ''),
        (193, 'Garment Steamers', 'Garment Steamer.jpg'),
        (194, 'Room Heaters', 'Room Heater.jpg'),
        (195, 'Electric Cookers', ''),
        (196, 'Lightning', ''),
        (197, 'Fashion & Grooming', ''),
        (198, 'Switches', ''),
        (199, 'Pumps', ''),
        (200, 'Switchgears', ''),
        (201, 'Air Cooler', 'Air Cooler.jpg')");
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('product_icons');
    }
}
